### ISSUE TITLE
libutility.so无法加载的问题

### ISSUE THREAD

**Issue by liujinchaoDS** [mabeijianxi/small-video-record#1]
导入的库中只有armeabi-v7a目录下有该so库，其他目录下没有，启动时有些手机无法找到对应的so库会崩溃

**Comment by mabeijianxi** [comment]
比如说哪些手机？不一定要有其他的，这个arm兼容性是最好的

**Comment by liujinchaoDS** [comment]
在项目中例如使用了fresco，它支持arm64-v8a，就会生成这个文件夹，但这个文件夹下没有libutility.so就会报错

**Comment by mabeijianxi** [comment]
我项目中也用到了fresco，测试已经测了快两个周，但是没有问题。而且据我所知，很大一部分的手机与cpu架构都是兼容armeabi-v7a的，鉴于你的情况可以网上看看资料，也可以不用arm64-v8a。或者在gradle里面配置abiFilters，如果有具体手机出现问题可以和我再交流下是哪些手机

**Comment by dalong982242260** [comment]
能不能多编译出几个so目录 现在比较常用的几个  x86 支持不

**Comment by liujinchaoDS** [comment]
方便的话还是请编译多个so好一些

**Comment by MrTrying** [comment]
在x86的模拟器上会奔溃，即使将libutility.so复制一份也是会报错的。这个能兼容一下么？

**Comment by dalong982242260** [comment]
同求

**Comment by mabeijianxi** [comment]
对于so库的问题这里做一个说明，现在使用的so库是秒拍用的底层so库，比较稳定，但不开源。对于现在市场占有率为8%的X86架构暂时不做处理。但我公司新版本上线后如果市场反馈有问题那么将会自己编写个简洁的FFmpeg库以做支持，届时也将抽时间维护本库的底层so。而现在只对Java层做维护。

**Comment by jockie911** [comment]
进入录像界面没有预览界面  必须切换摄像头才能正常预览

**Comment by jockie911** [comment]
应该是6.0权限问题

**Comment by qujc** [comment]
我遇到个问题，我一开始在一款手机上可以运行这个库，但是今天调试程序的时候突然发现报错，提示找不到so文件，有谁遇到过这个问题吗？

**Comment by jockie911** [comment]
可以这样设置 ndk{abiFilters "armeabi-v7a"}

在 2016-10-22 00:25:20，"qujc" <notifications@github.com> 写道：


我遇到个问题，我一开始在一款手机上可以运行这个库，但是今天调试程序的时候突然发现报错，提示找不到so文件，有谁遇到过这个问题吗？

**Comment by qujc** [comment]
@jockie911 按照你的提示，确实可以了，非常感谢~~ 但是为什么我单独运行demo没有这个问题，放到我自己的工程里就会报错呢？

**Comment by liujinchaoDS** [comment]
@qujc 你的工程里有其他CPU架构，会生成对应的目录，而该项目只包含v7a，除v7a外，其他目录没有so库，对应的目录下找不到so库就会报错，所以使用如上配置会只保留v7a架构，其他目录都会被删除，保证能找到so库。
