### ISSUE TITLE
small-video-record2.0里的sample对width和height设定对录制后视频无效

### ISSUE THREAD

**Issue by ansonlo** [mabeijianxi/small-video-record#101]
small-video-record2.0，里的sample项目，运行后对width和height怎么设定，录制得到视频还是480*360呢？

**Comment by mabeijianxi** [comment]
请看清楚注释，1.0的宽，2.0的高不能随意传入，必须是手机所支持的，不然就使用默认。而且所支持的我已经全部在输入框上面打印出来了

**Comment by ansonlo** [comment]
但我测试按照sample的提示，输入高度720，由于宽度没提示多少，我就输入640，录制完后就崩了

**Comment by mabeijianxi** [comment]
日志提示是什么错误

**Comment by mabeijianxi** [comment]
我这边试了这种分辨率暂时没发现错误
