### ISSUE TITLE
华为p9录制720*1280分辨率视频转码失败。

### ISSUE THREAD

**Issue by YuChuanchun** [mabeijianxi/small-video-record#105]
width:720,height:1280,视频转码失败，width：1280， height：720转码成功。

**Comment by mabeijianxi** [comment]
版本号

**Comment by YuChuanchun** [comment]
1.2.2版本

**Comment by mabeijianxi** [comment]
你debug看下获取摄像头所支持的尺寸时，720匹配的是多少，如果匹配值小于你输入的1280可能就会失败，比如匹配960，你不可能编码出来一个1280

**Comment by YuChuanchun** [comment]
这个我打印出来看过了，摄像头支持录制720*1280的，m2 note上面是的，不知道为什么p9上面就转码失败。

**Comment by ansonlo** [comment]
这个问题也发生在华为mate8，我从代码里 
Camera back = Camera.open(Camera.CameraInfo.CAMERA_FACING_BACK);
List<Camera.Size> backSizeList = back.getParameters().getSupportedPreviewSizes();

然后在页面设置里符合结果的width和height，也会编码失败，崩了

**Comment by mabeijianxi** [comment]
不是光支持就可以了，比如其支持的有720*960、720*1280，在循环查找过程中，可能由于960的排在前面，所以没有选择1280

**Comment by ansonlo** [comment]
@mabeijianxi 你这个说法我没理解到，那究竟是以什么的方式能查询到，可以作为支持呢？

**Comment by mabeijianxi** [comment]
很好理解啊，getSupportedPreviewSizes返回的是一个列表，是有顺序的，我们的逻辑是找到720的就停止，且取其对应的值，里面可能有两个720的，先找到的可能不是我们需要的。

**Comment by YuChuanchun** [comment]
demo里面不是可以输入width和height吗，代码里面没有看到其他地方去改了这个我们设置的宽高值。我怀疑是libutility.so里面编码的时候出了问题。

**Comment by mabeijianxi** [comment]
请仔细看了源码！这块儿代码是我后来加上去的，怎么会没有。建议用2.0+版本了
