### ISSUE TITLE
部分手机空指针

### ISSUE THREAD

**Issue by cat1024** [mabeijianxi/small-video-record#111]

**Comment by cat1024** [comment]
mMediaObject = mMediaRecorder.setOutputDirectory(key,
                JianXiCamera.getVideoCachePath() + key);
mMediaObject 空指针现象sony 4.4系统

**Comment by InterestingYuTou** [comment]
哇 我也是这个空指针哎 发现是mMediaObject是空的 不知道怎么回事

**Comment by InterestingYuTou** [comment]
File f = new File(JianXiCamera.getVideoCachePath());我是MediaRecorderActivity创建文件的时候就报空指针了 估计是后面路径是空的

**Comment by InterestingYuTou** [comment]
我知道了 你看看有没有初始化这个方法initSmallVideo( ) 创建路径啥的

**Comment by mabeijianxi** [comment]
是的，你需要先 init
