### ISSUE TITLE
如果时间过短，没有缩略图，而且偶尔会出现数据丢失的情况

### ISSUE THREAD

**Issue by SilenceGo** [mabeijianxi/small-video-record#112]
1.没有缩略图：在视频录制时间0-7s之内偶尔会出现
2.数据丢失：明明录制15s的视频，偶尔会出现只有2-5s的情况。

**Comment by mabeijianxi** [comment]
缩略图那个如果你一开始镜头里是黑的的话可能取的帧就是一张黑图，因为去的是1毫秒位置的，并非没有，我测试的时候发现的，你可以检查下缓存目录下是否真的生成了图片。第二个问题还没复现过，我得在试试

**Comment by SilenceGo** [comment]
缩略图这个问题，我已经解决了，使用ThumbnailUtils类可以解决，但是数据丢失这个问题确实存在

**Comment by SilenceGo** [comment]
亲测在魅蓝note2手机上存在该问题，不知道是不是CPU架构的问题，

**Comment by SilenceGo** [comment]
亲测在魅蓝note2上存在该情况，部分手机录制时间短都会出现这个情况，不知道是不是CPU架构的问题，

**Comment by mabeijianxi** [comment]
这样，你打开缓存目录，然后播放下里面的 AAC 文件，也就是音频，你看它时间长度对不对

**Comment by SilenceGo** [comment]
1.没有音频文件，可能是录音权限被 禁止，
2.只有mp4文件,而且时间长度也不对，
3,如果没有jpg文件的话,也就没有缩略图
现在我手机也出现这种情况了，而且在使用中发现，只有armeabi-v7的so库，没有arm64-v8a的so库，，，

**Comment by SilenceGo** [comment]
而且现在这个问题，用ThumbnailUtils也没法解决缩略图的问题了，因为为缩略图的路径校验一直用TextUtils校验是否为空，但发现没缩略图的时候，仍可以规避非空校验，继而界面部分显示空白。。

**Comment by mabeijianxi** [comment]
2.0.0 正式版刚提交完成，已编译全平台，使用方式也更加解耦，但和以前略有不同，使用前请参看使用文档！
