### ISSUE TITLE
录制视频时会有卡顿的现象

### ISSUE THREAD

**Issue by cat1024** [mabeijianxi/small-video-record#113]

**Comment by mabeijianxi** [comment]
版本，机型，必现还是偶尔啊？

**Comment by cat1024** [comment]
@mabeijianxi    就是你最新更新的那个版本，手机是红米note4 6.0系统。。。录制时间设置的是1分钟，如果是默认360X480，倒没什么问题。。设置更高的之后，录制到后面就会出现卡顿，时间越长卡顿严重。。必现的。然后录制后视频处理时间太长了。。。一分钟大概需要三分钟后处理时间、、、这个是否有优化的空间呢？

**Comment by mabeijianxi** [comment]
嗯，你录制久了卡顿可能是你手机 cpu 跟不上，这个软编太吃 cpu 了，你尺寸越大数据量也越大，编码时间也就越久，这个库本来是用来录制小视频的，所以更变向于高压缩比，后期会考虑暴露个偏好选择，到时候就可以在高压缩比与高速完成之间做一个选择

**Comment by mabeijianxi** [comment]
使用最新版本，如果支持 64 位将达到0延迟
