### ISSUE TITLE
红米，Nubia等手机报couldn't find "libjx_ffmpeg_jni.so"

### ISSUE THREAD

**Issue by zpliang94** [mabeijianxi/small-video-record#117]
nexus5没有问题，我是把smallVideolib作为module导入项目的

**Comment by mabeijianxi** [comment]
你直接跑demo或者我编译好的apk有问题没？你项目里面是不是用了其他架构的so？如果你项目里面是 armeabi 的话你需要把我这边的so换到 armeabi 下或者 把你的换到  armeabi-v7a 下

**Comment by zpliang94** [comment]
使用smallVideolib2的demo红米手机是问题的，项目里有环信，支付的so文件，我把smallVideolib2里的so文件放到主module里也不可以

**Comment by zpliang94** [comment]
@mabeijianxi 使用smallVideolib2的demo红米手机是问题的，项目里有环信，支付的so文件，我把smallVideolib2里的so文件放到主module里也不可以

**Comment by zpliang94** [comment]
@mabeijianxi 使用smallVideolib2的demo红米手机是没有问题的。目前项目里有环信，支付的so文件，我把smallVideolib2里的so文件放到主module里armeabi-v7a红米手机也不可以运行

**Comment by zpliang94** [comment]
@mabeijianxi 找到问题了，红米note2一些64位手机是加载arm64-v8a的so文件的，所以无法找到so文件，而nexus5是32是可以的

**Comment by mabeijianxi** [comment]
这是个很常见的问题，应该是 so 不全导致的，你有些 so 只有 armeabi-v7a，有些又只有 armeabi，你需要统一。单说项目的话你可以 直接运行Demo ，看是否有问题

**Comment by zpliang94** [comment]
@mabeijianxi 直接运行Demo是没有问题的

**Comment by zpliang94** [comment]
@mabeijianxi 就是导入我项目出问题

**Comment by zpliang94** [comment]
@mabeijianxi 可以提供一个全的的so文件码

**Comment by mabeijianxi** [comment]
解决办法已经给你说了啊，除了X86架构 它们是兼容发，你copy 下即可
