### ISSUE TITLE
x86 arch not compiling 

### ISSUE THREAD

**Issue by hubcin** [mabeijianxi/small-video-record#118]
I added abiFilter "x86" and find it doesn't compile, did you try this ?

**Comment by mabeijianxi** [comment]
Because FFmpeg compiler arm architecture, if you need x86 architecture, you need to modify the FFmpeg compiler script.

**Comment by mabeijianxi** [comment]
因为 FFmpeg 编译的是 arm 架构的，如果你需要 x86 架构的，你需要修改下目录下的 FFmpeg 编译脚本

**Comment by hubcin** [comment]
OK, I'll try that , thanks
