### ISSUE TITLE
x86，全屏拍摄

### ISSUE THREAD

**Issue by yale8848** [mabeijianxi/small-video-record#119]
1.麻烦问问用你的工程如何编译x86 so库？
2.如果要全屏拍摄，是要自己动态算宽高吗？

**Comment by mabeijianxi** [comment]
目录下不是有个ffmpeg 的目录嘛。进去有个编译脚本，改成 x86 模式编译即可，里面的 x264 与 fdk-aac 也相应的得先重新编译为 x86的，一般没必要用 x86的，全屏得更改ui,不然录制键都出不来

**Comment by mabeijianxi** [comment]
已经编译全平台，且支持全屏录制

**Comment by yale8848** [comment]
非常感谢：）
