### ISSUE TITLE
考虑把这个库做成能自定义UI吗？

### ISSUE THREAD

**Issue by lala9662** [mabeijianxi/small-video-record#120]
或者先弄成可以修改录制界面上的图标和文字吧。。。

希望至少先把那个layout的一些属性暴露出来可以稍微修改一下。。。

当然最好是可以自定义这个录制界面啦，然后布局里只要引用你封装好的View就好了。。。

现在只能自己拉下来改着用-。-

**Comment by mabeijianxi** [comment]
后期稳定了会考虑优化
