### ISSUE TITLE
红米3S  压缩视频出错

### ISSUE THREAD

**Issue by linqssonny** [mabeijianxi/small-video-record#123]
doCompress->
com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.jxFFmpegCMDRun->
com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.jxCMDRun->
/lib/arm/libjx_ffmpeg_jni.so(Java_com_mabeijianxi_smallvideorecord2_jniinterface_FFmpegBridge_jxCMDRun+104)->
/lib/arm/libjx_ffmpeg_jni.so (jxRun+442)->
/lib/arm/libjx_ffmpeg_jni.so->
lib/arm/libavfilter.so (av_buffersink_get_frame_rate+5)->
报了一下错误：
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x41
    r0 d50ff138  r1 acd07790  r2 ed12e3ee  r3 00000041
    r4 ad0415d4  r5 acd07790  r6 00000001  r7 d50ff190
    r8 abba7300  r9 ace5f940  sl ac93f610  fp aca9aa30
    ip ddf5ba74  sp d50fdb48  lr ddf2761f  pc ddfab6ca  cpsr 600f0030

备注：我用红米3s相机拍摄视频，然后压缩不会出现该问题，但利用MediaRecorder、MediaProjection、VirtualDisplay对手机进行录像，就会出现该问题，代码调用如下：
LocalMediaConfig.Buidler buidler = new LocalMediaConfig.Buidler();
                    final LocalMediaConfig config = buidler
                            .setVideoPath(videoPath)
                            .captureThumbnailsTime(1)
                            .doH264Compress(new AutoVBRMode())
                            .setFramerate(15)
                            .setScale(scale)
                            .build();
compressOverBean = new LocalMediaCompress(config).startCompress();

**Comment by linqssonny** [comment]
nexus 5x、 三星s6也会

**Comment by linqssonny** [comment]
Parsing a group of options: output url /storage/emulated/0/cubed/1498464598657/1498464598657.mp4.
Applying option c:v (codec name) with argument libx264.
Applying option c:a (codec name) with argument libfdk_aac.
Applying option r (set frame rate (Hz value, fraction or abbreviation)) with argument 24.
Successfully parsed a group of options.
Opening an output file: /storage/emulated/0/cubed/1498464598657/1498464598657.mp4.
Setting default whitelist 'file,crypto'
Successfully opened the file.
detected 4 logical cores
Setting 'video_size' to value '360x598'
Setting 'pix_fmt' to value '0'
Setting 'time_base' to value '1/90000'
Setting 'pixel_aspect' to value '1/1'
Setting 'sws_param' to value 'flags=2'
Setting 'frame_rate' to value '3540000/120793'
w:360 h:598 pixfmt:yuv420p tb:1/90000 fr:3540000/120793 sar:1/1 sws_param:flags=2
compat: called with args=[yuv420p|yuvj420p|yuv422p|yuvj422p|yuv444p|yuvj444p|nv12|nv16|nv21]
Setting 'pix_fmts' to value 'yuv420p|yuvj420p|yuv422p|yuvj422p|yuv444p|yuvj444p|nv12|nv16|nv21'
query_formats: 4 queried, 3 merged, 0 already done, 0 delayed
No decoder for stream #0:1, filtering impossible
Error opening filters!
Quit at 1Statistics: 0 seeks, 0 writeouts
Statistics: 346459 bytes read, 3 seeks

**Comment by linqssonny** [comment]
http://blog.csdn.net/u013375059/article/details/54287426
第二种方式录的视频无法压缩，第三种可以

**Comment by mabeijianxi** [comment]
你这个正常，我为了so更小开启的编解码库很少的，你如何需要更多格式的改下  FFmpeg 目录下编译脚本然后重新编译下就行了，全格式可能会达到10多兆。你这也是种问题，正式版的时候我再编好一份放目录下需要的可以 copy

**Comment by linqssonny** [comment]
那目前支持的解码库有哪些呢？  我看我这边能不能改
