### ISSUE TITLE
notifyState(int state,float what)

### ISSUE THREAD

**Issue by diycoder** [mabeijianxi/small-video-record#128]
博主，请问你这个方法在哪里调用
 /**
     * 底层回调
     * @param state
     * @param what
     */
    public static synchronized void notifyState(int state,float what){
        for(FFmpegStateListener listener: listeners){
            if(listener!=null){
                if(state== ALL_RECORD_END){
                    listener.allRecordEnd();
                }
            }
        }
    }

**Comment by diycoder** [comment]
我只改了一下包名，相关联的路径也该了，重新编译调用生成的so，是在Fragment中录制视频，第一次是没问题的，第二次录制就崩溃报这个异常，偶尔出现，请问是什么问题?
06-27 15:51:37.756 31515-31515/? A/DEBUG: ABI: 'arm'
06-27 15:51:37.756 31515-31515/? A/DEBUG: pid: 14997, tid: 30849, name: Thread-13  >>> com.xxx.xxxx <<<
06-27 15:51:37.756 31515-31515/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
06-27 15:51:37.756 31515-31515/? A/DEBUG:     r0 00000000  r1 00000000  r2 ed4d16e3  r3 c1650ec0
06-27 15:51:37.756 31515-31515/? A/DEBUG:     r4 ed4d16e3  r5 c1651b48  r6 c16518f0  r7 c1651318
06-27 15:51:37.756 31515-31515/? A/DEBUG:     r8 c16518f0  r9 bdffb000  sl 00000000  fp c165187c
06-27 15:51:37.756 31515-31515/? A/DEBUG:     ip c1650ee8  sp c1650fd0  lr ed4d16e3  pc c7223c00  cpsr 880e0030
06-27 15:51:37.758 31515-31515/? A/DEBUG: backtrace:
06-27 15:51:37.758 31515-31515/? A/DEBUG:     #00 pc 0002fc00  /data/app/com.xxx.xxxx-1/lib/arm/libjx_ffmpeg_jni.so
06-27 15:51:37.758 31515-31515/? A/DEBUG:     #01 pc 0002d9d7  /data/app/com.xxx.xxxx-1/lib/arm/libjx_ffmpeg_jni.so
06-27 15:51:37.758 31515-31515/? A/DEBUG:     #02 pc 0002d845  /data/app/com.xxx.xxxx-1/lib/arm/libjx_ffmpeg_jni.so (ffmpeg_parse_options+220)
06-27 15:51:37.758 31515-31515/? A/DEBUG:     #03 pc 0001ca67  /data/app/com.xxx.xxxx-1/lib/arm/libjx_ffmpeg_jni.so (jxRun+366)
06-27 15:51:37.758 31515-31515/? A/DEBUG:     #04 pc 00037205  /data/app/com.xxx.xxxx-1/lib/arm/libjx_ffmpeg_jni.so (ffmpeg_cmd_run+20)
06-27 15:51:37.759 31515-31515/? A/DEBUG:     #05 pc 000371b7  /data/app/com.xxx.xxxx-1/lib/arm/libjx_ffmpeg_jni.so (Java_com_xxx_xxxx_FFmpegBridge_jxCMDRun+226)
06-27 15:51:37.759 31515-31515/? A/DEBUG:     #06 pc 008696e1  /data/app/com.xxx.xxxx-1/oat/arm/base.odex (offset 0x831000)

**Comment by mabeijianxi** [comment]
你不能随便改包名，如果一定要改，需要把底层的 JNI 函数也改了，你说的那个方法就是在底层通过反射调用的

**Comment by mabeijianxi** [comment]
你不能随便改 FFmpegBridge 的路径，如果一定要改，需要把底层的 JNI 函数也改了，你说的那个方法就是在底层通过反射调用的

**Comment by diycoder** [comment]
底层的 JNI 函数我都改了，但是断点录制的时候会报这个错，还有我发现音频和视频不同步，音频比视频快，只是做了简单的音频和视频合成，时间戳貌似没对上

**Comment by mabeijianxi** [comment]
只要设置的采集参数和实际采集数据没问题，就能同步上，比如你设置每秒 25 帧，但是如果实际每秒只采集了 20 帧，这个时候合成计算的时候就会出问题，导致视音不同步了。我一开始做的时候就出现了不停步的问题，后来采用容器存放和 3个 buffer 的方式解决了,如果你还是觉得视频比音频慢你换成 4个 buffer 来接收 视频帧试试

**Comment by erleizh** [comment]
@diycoder 你第二次录制崩溃是咋改的
