### ISSUE TITLE
用模拟器录制会崩溃的问题

### ISSUE THREAD

**Issue by qiaoqileng** [mabeijianxi/small-video-record#130]
2017年6月28日最新下载的demo运行在海马玩模拟器上崩溃
06-28 10:29:15.767 13716-13716/com.mabeijianxi.smallvideo W/EGL_emulation: eglSurfaceAttrib not implemented
06-28 10:29:15.767 13716-13716/com.mabeijianxi.smallvideo E/YXLog: action_action 5 start 
06-28 10:29:15.783 13716-13716/com.mabeijianxi.smallvideo E/YXLog: action_action 5 finish 100
06-28 10:29:15.795 13716-16948/com.mabeijianxi.smallvideo E/YXLog: cmdline sync: ffmpeg  -d stdout -loglevel verbose -i "/mnt/sdcard/DCIM/mabeijianxi/1498616924559/0.ts" -vcodec copy -acodec copy -absf aac_adtstoasc -f mp4 -movflags faststart "/mnt/sdcard/DCIM/mabeijianxi/1498616924559/1498616924559_temp.mp4" 
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Splitting the commandline.
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Reading option '-loglevel' ...
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog:  matched as option 'loglevel' (set logging level) with argument 'verbose'.
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Reading option '-i' ...
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog:  matched as input file with argument '/mnt/sdcard/DCIM/mabeijianxi/1498616924559/0.ts'.
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Reading option '-vcodec' ...
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog:  matched as option 'vcodec' (force video codec ('copy' to copy stream)) with argument 'copy'.
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Reading option '-acodec' ...
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog:  matched as option 'acodec' (force audio codec ('copy' to copy stream)) with argument 'copy'.
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Reading option '-absf' ...
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog:  matched as option 'absf' (deprecated) with argument 'aac_adtstoasc'.
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Reading option '-f' ...
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog:  matched as option 'f' (force format) with argument 'mp4'.
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Reading option '-movflags' ...
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog:  matched as AVOption 'movflags' with argument 'faststart'.
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Reading option '/mnt/sdcard/DCIM/mabeijianxi/1498616924559/1498616924559_temp.mp4' ...
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog:  matched as output file.
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Finished splitting the commandline.
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Parsing a group of options: global .
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Applying option loglevel (set logging level) with argument verbose.
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Successfully parsed a group of options.
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Parsing a group of options: input file /mnt/sdcard/DCIM/mabeijianxi/1498616924559/0.ts.
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Successfully parsed a group of options.
06-28 10:29:15.799 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Opening an input file: /mnt/sdcard/DCIM/mabeijianxi/1498616924559/0.ts.
06-28 10:29:15.819 13716-16948/com.mabeijianxi.smallvideo D/YXLog: Format mpegts probed with size=2048 and score=100
06-28 10:29:15.819 13716-16948/com.mabeijianxi.smallvideo D/YXLog: stream=0 stream_type=1b pid=100 prog_reg_desc=
06-28 10:29:15.819 13716-16948/com.mabeijianxi.smallvideo D/YXLog: stream=1 stream_type=f pid=101 prog_reg_desc=
06-28 10:29:15.819 13716-16948/com.mabeijianxi.smallvideo D/YXLog: File position before avformat_find_stream_info() is 0
06-28 10:29:15.903 13716-16948/com.mabeijianxi.smallvideo A/libc: Fatal signal 11 (SIGSEGV) at 0xdead0000 (code=1), thread 16948 (AsyncTask #1)

**Comment by mabeijianxi** [comment]
有so库，最好用真机
