### ISSUE TITLE
请问下 2.0版本demo 本地压缩是否已经是多线程实现了？

### ISSUE THREAD

**Issue by androidCoderxiao** [mabeijianxi/small-video-record#134]
我看了源码DEMO 好像没看见相关实现。请问在JAVA层需要怎实现？

**Comment by mabeijianxi** [comment]
编译 FFmpeg 的时候已经开启多线程配置，且在压缩命令中也指定了线程数目，不指定的话 FFmpeg 默认启用线程数为 3/2*核数
