### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by KarasJoker** [mabeijianxi/small-video-record#136]
01-04 07:05:25.530 17908-17908/com.tulong.tlpet D/AndroidHeapDumper: Previous analysis did not complete correctly, cleaning: /data/data/com.tulong.tlpet/files/suspected_leak_heapdump.hprof
01-04 07:05:25.570 17908-17908/com.tulong.tlpet I/dalvikvm: Could not find method com.tulong.tlpet.view.activity.BaseActivity.checkSelfPermission, referenced from method com.tulong.tlpet.view.activity.BaseActivity.getCameraPermissions
01-04 07:05:25.570 17908-17908/com.tulong.tlpet W/dalvikvm: VFY: unable to resolve virtual method 54586: Lcom/tulong/tlpet/view/activity/BaseActivity;.checkSelfPermission (Ljava/lang/String;)I
01-04 07:05:25.570 17908-17908/com.tulong.tlpet D/dalvikvm: VFY: replacing opcode 0x6e at 0x000d
01-04 07:05:25.570 17908-17908/com.tulong.tlpet I/dalvikvm: Could not find method com.tulong.tlpet.view.activity.BaseActivity.checkSelfPermission, referenced from method com.tulong.tlpet.view.activity.BaseActivity.onCreate
01-04 07:05:25.570 17908-17908/com.tulong.tlpet W/dalvikvm: VFY: unable to resolve virtual method 54586: Lcom/tulong/tlpet/view/activity/BaseActivity;.checkSelfPermission (Ljava/lang/String;)I
01-04 07:05:25.570 17908-17908/com.tulong.tlpet D/dalvikvm: VFY: replacing opcode 0x6e at 0x0028
01-04 07:05:25.580 17908-17908/com.tulong.tlpet V/HwWidgetFactory: : successes to get AllImpl object and return....
01-04 07:05:25.580 17908-17908/com.tulong.tlpet I/dalvikvm: Could not find method android.view.Window$Callback.onProvideKeyboardShortcuts, referenced from method android.support.v7.view.WindowCallbackWrapper.onProvideKeyboardShortcuts
01-04 07:05:25.580 17908-17908/com.tulong.tlpet W/dalvikvm: VFY: unable to resolve interface method 22241: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
01-04 07:05:25.580 17908-17908/com.tulong.tlpet D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
01-04 07:05:25.580 17908-17908/com.tulong.tlpet W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
01-04 07:05:25.580 17908-17908/com.tulong.tlpet I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
01-04 07:05:25.580 17908-17908/com.tulong.tlpet W/dalvikvm: VFY: unable to resolve interface method 22243: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
01-04 07:05:25.580 17908-17908/com.tulong.tlpet D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
01-04 07:05:25.580 17908-17908/com.tulong.tlpet I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
01-04 07:05:25.580 17908-17908/com.tulong.tlpet W/dalvikvm: VFY: unable to resolve interface method 22247: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
01-04 07:05:25.580 17908-17908/com.tulong.tlpet D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
01-04 07:05:25.580 17908-17908/com.tulong.tlpet I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
01-04 07:05:25.580 17908-17908/com.tulong.tlpet W/dalvikvm: VFY: unable to resolve virtual method 681: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
01-04 07:05:25.580 17908-17908/com.tulong.tlpet D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
01-04 07:05:25.580 17908-17908/com.tulong.tlpet I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
01-04 07:05:25.580 17908-17908/com.tulong.tlpet W/dalvikvm: VFY: unable to resolve virtual method 703: Landroid/content/res/TypedArray;.getType (I)I
01-04 07:05:25.580 17908-17908/com.tulong.tlpet D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
01-04 07:05:25.630 17908-17908/com.tulong.tlpet D/AndroidRuntime: Shutting down VM
01-04 07:05:25.630 17908-17908/com.tulong.tlpet W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x417e5c68)

**Comment by KarasJoker** [comment]
大神，我一运行就报这个，就崩溃了。怎么办，是什么原因啊

**Comment by mabeijianxi** [comment]
人家不是说了，你没那个方法。你这不是我的包名，你下载 apk 试试
