### ISSUE TITLE
我使用MediaRecoderNative录制的视频无法在海马玩模拟器播放，而使用MediaRecorderSystem录制的视频可以在海马玩模拟器播放

### ISSUE THREAD

**Issue by SeniorDoctorHui** [mabeijianxi/small-video-record#139]
我使用的1.0.7的版本，但是我用你1.2.0的demo录制完发现海马玩模拟器也不支持这种视频播放。原因应该是不支持这种编码。请问用这两种类录制的视频编码有什么区别吗？

**Comment by SeniorDoctorHui** [comment]
这个问题暂时只在海马玩模拟器出现，但是我想在一些低配的手机也有可能出现此类问题，所以想问下有什么办法优化下，使得录制的视频能更好地兼容各类手机。

**Comment by mabeijianxi** [comment]
架构原因，预计这周末编译全架构

**Comment by mabeijianxi** [comment]
2.0.0 正式版刚提交完成，已编译全平台，使用方式也更加解耦，但和以前略有不同，使用前请参看使用文档！
