### ISSUE TITLE
Android N上集成 百度SDK 后,是否只能 支持 CPU 架构为 arm-v7a,之前未新建5种CPU架构 的文件夹,目前在Android 7.0 CPU 架构为arm64-v8a 报错

### ISSUE THREAD

**Issue by d-yh** [mabeijianxi/small-video-record#140]
java.lang.UnsatisfiedLinkError
dlopen failed: library "/product/lib64/libavutil.so" needed or dlopened by "/vendor/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"

是否需要重新您的源码,支持多种CPU架构

**Comment by mabeijianxi** [comment]
我会尽快支持全架构，但是你要清楚用 arm64-v8a 意味着 minSDk 是21

**Comment by mabeijianxi** [comment]
我会尽快支持全架构，预计这个周末弄

**Comment by mabeijianxi** [comment]
2.0.0 正式版刚提交完成，已编译全平台，使用方式也更加解耦，使用前请参看使用文档
