### ISSUE TITLE
2.0不录制直接点back返回会崩溃

### ISSUE THREAD

**Issue by lala9662** [mabeijianxi/small-video-record#141]
就是点手机的返回按钮，在录制界面不录制返回，你的2.0的demo就会崩溃。。。我在几台机都这样应该是代码有问题？1.0没这个问题。。。

**Comment by lala9662** [comment]
能不能先修一下这个bug啊。。。

**Comment by lala9662** [comment]
大概看了一下是onpause的时候就会触发onEncodeStart方法（开始转码了？？？），而1.0的sample是不会的。。。

**Comment by mabeijianxi** [comment]
是个 bug ，随着正式版一起修复

**Comment by mabeijianxi** [comment]
2.0.0正式版已修复
