### ISSUE TITLE
命令行确实可以转格式，但是如果我想转格式并压缩怎么搞呢？

### ISSUE THREAD

**Issue by xiejinsorry** [mabeijianxi/small-video-record#144]
另外转格式好像要输入视频分辨率怎么获取视频分辨率呢？

**Comment by mabeijianxi** [comment]
转码的时候我预设了那么多参数，你配置低点不就压缩了么。分辨率也不需要你获取，如果你一定要获取也是可以的，Java 代码获取的话看我本地压缩那个类就可以了
