### ISSUE TITLE
转换格式报错，帮忙看一下这个代码，急

### ISSUE THREAD

**Issue by xiejinsorry** [mabeijianxi/small-video-record#146]
错误 /libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 4888  
private static void processFLV(String resourcePath) {
        if (!checkfile(resourcePath)) {
            System.err.println(resourcePath + " is not file");
        }
        // 文件命名
        //Calendar c = Calendar.getInstance();
        //String savename = String.valueOf(c.getTimeInMillis()) + Math.round(Math.random() * 100000);
        String comm = "";
        comm = comm + "ffmpeg";
        comm = comm + " -i ";
        comm = comm + resourcePath.replaceAll(" ", "\" \"");
        comm = comm + " -ab";
        comm = comm + " 56";
        comm = comm + " -ar";
        comm = comm + " 22050";
        comm = comm + " -qscale";
        comm = comm + " 8";
        comm = comm + " -r";
        comm = comm + " 15";
        comm = comm + " -s ";
        comm = comm + Constant.WIDTH + "x" + Constant.HEIGHT + " ";
        comm = comm + targetPath.replaceAll(" ", "\" \"");
        try {
/*			Runtime runtime = Runtime.getRuntime();
            Process proce = null;
			String cmd = "";
			String cut = "F://ffmpeg.exe -i" + resourcePath + " -y -f image2   -ss   8   -t   0.001   -s   1366x768   D:\\snapshot\\" + savename + ".jpg";
			String cutCmd = cmd + cut;
			//proce = runtime.exec(comm);
*/
//            Runtime.getRuntime().exec(comm);
            FFmpegBridge.jxFFmpegCMDRun(comm);
            retryTimes = 60;

            //System.out.println("目标地址："+targetPath + "video.flv");
            System.out.println("正在转换视频...");
            File oldFile = new File(targetPath);
            boolean aFlag = true;
            int RetryTimes = 0;
            while (aFlag) {
                RetryTimes++;
                if (RetryTimes == retryTimes) {
                    RetryTimes = 0;
                    System.out.println("转换视频失败！重试次数：" + retryTimes + "*1s");
                    result = "转换视频失败！重试次数：" + retryTimes + "*1s";
                    aFlag = false;
                }
                if (oldFile.exists()) {
                    System.out.println("转换视频完成！");
                    result = "转换视频完成！";
                    aFlag = false;
                }
                Thread.sleep(1000);
            }
            new File(resourcePath).delete();

        } catch (Exception e) {
            System.err.println("发生异常，转换视频失败！异常信息：" + e.getMessage());
            result = "发生异常，转换视频失败！";
            //e.printStackTrace();
        }
    }

**Comment by mabeijianxi** [comment]
打开 debug ，将会生成 ffmpeg 的日志，里面有详细信息，单看这个我也看不出来
