### ISSUE TITLE
couldn't find "libjx_ffmpeg_jni.so"

### ISSUE THREAD

**Issue by csr91706** [mabeijianxi/small-video-record#150]
使用你的smallvideo2的demo运行，添加 compile 'com.facebook.fresco:fresco:1.3.0'就会提示找不到这个so，请问怎么解决，我的项目里有很多地方用到这个。
![0ff962d6-af0a-76af-95ec-a376bc0fb99c](https://user-images.githubusercontent.com/7697993/27845140-95b5ee9a-615e-11e7-9d4d-5730884611a1.png)
![aae80cf7-33e1-a4d2-e471-982a7995caef](https://user-images.githubusercontent.com/7697993/27845141-95c1335e-615e-11e7-8293-f24753ee9a80.png)

**Comment by mabeijianxi** [comment]
so 不全导致的，全平台的将会随着 2.0.0 正式版一起发，预计这周完成，到时候将不会出现这个问题，且性能得到大幅度提升

**Comment by csr91706** [comment]
项目急需上线，有办法加快完成吗

**Comment by mabeijianxi** [comment]
2.0.0 正式版刚提交完成，已编译全平台，使用方式也更加解耦，具体参看使用文档
