### ISSUE TITLE
用项目中ffmpeg命令可以 做视频的其他操作吗

### ISSUE THREAD

**Issue by kangjie6501** [mabeijianxi/small-video-record#151]

**Comment by mabeijianxi** [comment]
可以，但是现在编译的库是精简版的，全功能的比较大。最新全功能、全平台的将会随着 2.0.0 正式版一起发，预计这周完成

**Comment by kangjie6501** [comment]
small-video-record2和small-video-record 都升级吗？

**Comment by mabeijianxi** [comment]
只升级 small-video-record2，刚更新完，可以试试
