### ISSUE TITLE
我在定制的Android设备上，做横屏拍摄，但是拍出来的视频旋转了90°，请问怎么修改

### ISSUE THREAD

**Issue by SophyCh** [mabeijianxi/small-video-record#153]
我修改了MediaRecorderActivity界面，并在MediaRecorderBase的startPreview()中修改Camera角度，
camera.setDisplayOrientation(0);      
 这样做预览界面方向正确了，但是拍出来的视频是旋转90°的，请问大神在哪里修改视频 的角度？

**Comment by mabeijianxi** [comment]
prepareJXFFmpegEncoder,修改传入参数，你是想横屏录制么？

**Comment by SophyCh** [comment]
是的，横屏录制。我找了一下，prepareJXFFmpegEncoder在SmallVideoRecord2里面。 我直接在SmallVideoLib里面改的，没有这个方法可用，而且也没有关联到SmallVideoRecord2。我要改用SmallVideoRecord2，然后在修改传入参数吗？

**Comment by mabeijianxi** [comment]
是的，因为没暴露这个接口。如果还有问题就需要去底层修改 c++ 函数了。

**Comment by HolickABC** [comment]
请问修改这个prepareJXFFmpegEncoder()方法的哪些参数，弄了半天没弄出来。。。
