### ISSUE TITLE
2.0.0 正式版以后如果采用手动复制 SO 的做法

### ISSUE THREAD

**Issue by 3kqing** [mabeijianxi/small-video-record#157]
2.0.0 正式版以后如果采用手动复制 SO 的做法，避免与大家项目不兼容。当然如果你采用直接导入 Module 的就不必如此，直接删减已导入的 SO 和修改，并修改 gradle 的 abiFilters 即可。

这句话没看懂啊

**Comment by mabeijianxi** [comment]
如果采用依赖远程仓库手动复制你需要的 so 到你主 Module 里面即可。如果是下载源码导入你的项目就删除你不需要的 SO 文件夹，然后把gradle 的 abiFilters 修改为与之对应即可
