### ISSUE TITLE
用了新的2.0@aar后ClassLoader referenced unknown path: /data/app/com.qlzgzg.ffmpeg-2/lib/arm

### ISSUE THREAD

**Issue by cornflower10** [mabeijianxi/small-video-record#158]
如下错误
E/HAL: load: id=gralloc != hmi->id=gralloc
W/System: ClassLoader referenced unknown path: /data/app/com.qlzgzg.ffmpeg-2/lib/arm
机型华为 MT7-TL00

**Comment by mabeijianxi** [comment]
先直接扫码二维码下载 apk 试试

**Comment by mabeijianxi** [comment]
最新的依赖与以前不同，使用前先看文档
