### ISSUE TITLE
你的smallVideoRecord2运行就崩溃乐视X5

### ISSUE THREAD

**Issue by csr91706** [mabeijianxi/small-video-record#163]
![ce50cddd-084f-e4e9-1346-da552aa9f33a](https://user-images.githubusercontent.com/7697993/27900330-85023132-6260-11e7-9296-ca59ab068038.png)

**Comment by csr91706** [comment]
![6118f3ce-7f76-b9ba-f24b-f5d0983fc612](https://user-images.githubusercontent.com/7697993/27900387-c50a9abc-6260-11e7-96ac-067891ac41c4.png)

**Comment by mabeijianxi** [comment]
你的也是直接扫描下载的 APK ？

**Comment by csr91706** [comment]
下载的apk运行没有问题

**Comment by mabeijianxi** [comment]
你确定下载的最新代码么，新代码中这个库我根本没在 Java 层中 load的

**Comment by csr91706** [comment]
是你最新的呀

**Comment by csr91706** [comment]
![ffe68fa9-94c4-def0-0f2d-f95dbf2dc50c](https://user-images.githubusercontent.com/7697993/27901146-83600f2c-6263-11e7-9e4d-ae10dbcdd696.png)

**Comment by mabeijianxi** [comment]
额。。apk 和代码是配套的啊，行吧我空了再看看吧

**Comment by mabeijianxi** [comment]
或者你打包签名再试试

**Comment by csr91706** [comment]
啊啊啊。我新建个项目，吧你的smallVideoLib2导进去，就调用初始化就崩溃了。。你试下会不会崩溃

**Comment by fengfutong** [comment]
我也出现你这个问题，#155 华为FRD-AL00

**Comment by mabeijianxi** [comment]
@csr91706 我自己开发的项目我这边试了所有测试机都是不会奔溃的

**Comment by csr91706** [comment]
方便加个qq吗 我的qq917063826 ，详细向您咨询下

**Comment by fengfutong** [comment]
我用另外一个android6.0的小米没问题，我的华为是frd-al00是7.0系统

**Comment by csr91706** [comment]
@mabeijianxi 确实小米手机没问题，乐视的手机会崩溃

**Comment by mabeijianxi** [comment]
问题已经修复，是我编译的是否加入了个 m 的数学函数库，结果有的手机不支持。。。，2.0.1 已经修复，你们再试试，没问题就关了

**Comment by mabeijianxi** [comment]
问题已经修复，是我编译的时候加入了个 m 的数学函数库，结果有的手机不支持。。。，2.0.1 已经修复，你们再试试，没问题就关了
