### ISSUE TITLE
使用small-video-record 1可以使用命令行，但是用small-video_record2 不行

### ISSUE THREAD

**Issue by xiejinsorry** [mabeijianxi/small-video-record#164]
如运行以下 简单命令      FFmpegBridge.jxFFmpegCMDRun("ffmpeg -i " + resourcePath + " " + targetPath)； 会报异常

**Comment by mabeijianxi** [comment]
如果不是命令有误就是命令不支持，2 是精简版，需要更强大的更能需要替换 so 库，我文档都有说明
