### ISSUE TITLE
点击录制崩溃

### ISSUE THREAD

**Issue by 18819318753** [mabeijianxi/small-video-record#165]
点击按住录制的时候，程序崩溃了
07-06 16:22:07.410 8957-8957/cn.ewhale.applemanor E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
07-06 16:22:07.412 8957-8957/cn.ewhale.applemanor E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.mabeijianxi.smallvideorecord2.model.MediaObject.getDuration()' on a null object reference

**Comment by mabeijianxi** [comment]
扫码下载的 apk?

**Comment by mabeijianxi** [comment]
你是不是没初始化？
