### ISSUE TITLE
视频拼接命令不能用

### ISSUE THREAD

**Issue by kangjie6501** [mabeijianxi/small-video-record#173]
String cmd1 = "ffmpeg -i \"concat:"+cmd+"\" -acodec copy -vcodec copy -absf aac_adtstoasc "+Environment.getExternalStorageDirectory().toString() +"/loveVideo/"+"00.ts"+"|"+Environment
                            .getExternalStorageDirectory().toString() +"/loveVideo/"+"0000.mp4";

**Comment by kangjie6501** [comment]
ffmpeg -i "Apache Sqoop Tutorial Part 1.mp4" -c copy -bsf:v h264_mp4toannexb -f mpegts intermediate1.ts
ffmpeg -i "Apache Sqoop Tutorial Part 2.mp4" -c copy -bsf:v h264_mp4toannexb -f mpegts intermediate2.ts
ffmpeg -i "Apache Sqoop Tutorial Part 3.mp4" -c copy -bsf:v h264_mp4toannexb -f mpegts intermediate3.ts
ffmpeg -i "Apache Sqoop Tutorial Part 4.mp4" -c copy -bsf:v h264_mp4toannexb -f mpegts intermediate4.ts
ffmpeg -i "concat:intermediate1.ts|intermediate2.ts|intermediate3.ts|intermediate4.ts" -c copy -bsf:a aac_adtstoasc "Apache Sqoop Tutorial.mp4"
这是拼接视频的命令 总是报c语言的错误

**Comment by wudifamo** [comment]
ffmpeg -i concat:/storage/emulated/0/videoparser/v1.ts|/storage/emulated/0/videoparser/VID_1499654806465.ts|/storage/emulated/0/videoparser/v2.ts|/storage/emulated/0/videoparser/VID_1499654816185.ts| -vcodec copy -acodec copy /storage/emulated/0/videoparser/1499654820477.ts

我也遇到了同样问题,mp4转ts没问题,拼接就崩溃
使用的是精简版,难道需要用完整版?

I/jianxi_ffmpeg: 命令开始
I/jianxi_ffmpeg: 注册清理完成
I/jianxi_ffmpeg: 注册完成编解码器
I/jianxi_ffmpeg: 开始执行清理
I/jianxi_ffmpeg: 清理完成
                                                                      
                                                                      --------- beginning of crash
07-10 10:49:37.447 21606-22768/com.lotto.videoparser A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 22768 (Thread-11306)

**Comment by kangjie6501** [comment]
我是用的完整版 崩溃
/arm/libjx_ffmpeg_jni.so (setup_find_stream_info_opts+15)
ng-1/lib/arm/libjx_ffmpeg_jni.so
/libjx_ffmpeg_jni.so
/libjx_ffmpeg_jni.so (ffmpeg_parse_options+174)
ng-1/lib/arm/libjx_ffmpeg_jni.so (jxRun+366)
ng-1/lib/arm/libjx_ffmpeg_jni.so (ffmpeg_cmd_run+20)
ng-1/lib/arm/libjx_ffmpeg_jni.so (Java_com_mabeijianxi_smallvideorecord

**Comment by wudifamo** [comment]
那只能求解作者了@mabeijianxi 
之前使用的是[https://github.com/WritingMinds/ffmpeg-android-java](url)这个拼接是正常的 但是太大了有20M+

**Comment by kangjie6501** [comment]
https://github.com/WritingMinds/ffmpeg-android-java 我用命令怎么只能显示版本  不能生成想要的文件

**Comment by wudifamo** [comment]
cmd不要ffmepg开头 直接-i concat...

**Comment by mabeijianxi** [comment]
周末是看看

**Comment by mabeijianxi** [comment]
周末我看看

**Comment by mabeijianxi** [comment]
这个问题已经弄好了，我还没合并到主分支上，用 dev [https://github.com/mabeijianxi/small-video-record/tree/dev](https://github.com/mabeijianxi/small-video-record/tree/dev) so 试试

**Comment by mabeijianxi** [comment]
这个问题已经弄好了，我试了可以通过 concat 合并 ts 文件，我还没合并到主分支上，用 dev [https://github.com/mabeijianxi/small-video-record/tree/dev](https://github.com/mabeijianxi/small-video-record/tree/dev) 分支上的 so 试试

**Comment by wudifamo** [comment]
用demo试了下确实可以了,但是我把SmallVideoLib2导入我的demo再依赖还是会崩溃,应该是我这边的问题了,不知道和`ndk {            abiFilters "armeabi-v7a"        }`有没有关系

**Comment by mabeijianxi** [comment]
@wudifamo 兄弟你再试试呢，可能是上次我没提完整，试好了反馈下，没问题我就合并分支了，还是在 dev 分支上

**Comment by wudifamo** [comment]
@mabeijianxi 可以了

**Comment by mabeijianxi** [comment]
@wudifamo ok
