### ISSUE TITLE
为什么我一运行FFmpegBridge.jxFFmpegCMDRun就崩溃呢错误日志也没法定位

### ISSUE THREAD

**Issue by jsonhu** [mabeijianxi/small-video-record#175]
07-10 16:31:31.192 2262-2262/com.example.huchengzhi.videocompressapp A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 2262 (ideocompressapp)
07-10 16:31:31.246 716-716/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-10 16:31:31.246 716-716/? A/DEBUG: Build fingerprint: 'Xiaomi/capricorn/capricorn:6.0.1/MXB48T/V8.5.2.0.MAGCNED:user/release-keys'
07-10 16:31:31.247 716-716/? A/DEBUG: Revision: '0'
07-10 16:31:31.247 716-716/? A/DEBUG: ABI: 'arm64'
07-10 16:31:31.248 716-716/? A/DEBUG: pid: 2262, tid: 2262, name: ideocompressapp  >>> com.example.huchengzhi.videocompressapp <<<
07-10 16:31:31.248 716-716/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
07-10 16:31:31.272 716-716/? A/DEBUG:     x0   0000007fb43c26c0  x1   0000000000000007  x2   0000000000000008  x3   000000000000003e
07-10 16:31:31.273 716-716/? A/DEBUG:     x4   0000000000000006  x5   00000000000000c4  x6   00000000000000c5  x7   0000007fb75ac000
07-10 16:31:31.273 716-716/? A/DEBUG:     x8   0000000000000001  x9   0000000000000000  x10  000000000a731080  x11  000000000a7310c0
07-10 16:31:31.273 716-716/? A/DEBUG:     x12  0000000000000000  x13  0000007fb75eb000  x14  0000000000000000  x15  0000007fb75dd000
07-10 16:31:31.273 716-716/? A/DEBUG:     x16  0000007fb75eeeb0  x17  0000007fb75dd000  x18  0000007fb75eef50  x19  0000000000000001
07-10 16:31:31.273 716-716/? A/DEBUG:     x20  259d7dcc2d5cef16  x21  0000007fb27351e0  x22  0000000000000000  x23  0000007fb27351d8
07-10 16:31:31.273 716-716/? A/DEBUG:     x24  0000000000000001  x25  0000000000000001  x26  0000007fb27351f8  x27  0000007fa817e940
07-10 16:31:31.273 716-716/? A/DEBUG:     x28  0000007fa81efba8  x29  0000007fd6149910  x30  0000007fb26dcba4
07-10 16:31:31.273 716-716/? A/DEBUG:     sp   0000007fd6149870  pc   0000007fb26e1614  pstate 0000000060000000
07-10 16:31:31.284 716-716/? A/DEBUG: backtrace:
07-10 16:31:31.284 716-716/? A/DEBUG:     #00 pc 0000000000023614  /data/app/com.example.huchengzhi.videocompressapp-2/lib/arm64/libjx_ffmpeg_jni.so
07-10 16:31:31.284 716-716/? A/DEBUG:     #01 pc 000000000001eba0  /data/app/com.example.huchengzhi.videocompressapp-2/lib/arm64/libjx_ffmpeg_jni.so
07-10 16:31:31.284 716-716/? A/DEBUG:     #02 pc 0000000000018cf8  /data/app/com.example.huchengzhi.videocompressapp-2/lib/arm64/libjx_ffmpeg_jni.so (exit_program+56)
07-10 16:31:31.284 716-716/? A/DEBUG:     #03 pc 000000000002d784  /data/app/com.example.huchengzhi.videocompressapp-2/lib/arm64/libjx_ffmpeg_jni.so
07-10 16:31:31.284 716-716/? A/DEBUG:     #04 pc 000000000002bde8  /data/app/com.example.huchengzhi.videocompressapp-2/lib/arm64/libjx_ffmpeg_jni.so
07-10 16:31:31.285 716-716/? A/DEBUG:     #05 pc 000000000002bbc4  /data/app/com.example.huchengzhi.videocompressapp-2/lib/arm64/libjx_ffmpeg_jni.so (ffmpeg_parse_options+188)
07-10 16:31:31.285 716-716/? A/DEBUG:     #06 pc 000000000001e5b8  /data/app/com.example.huchengzhi.videocompressapp-2/lib/arm64/libjx_ffmpeg_jni.so (jxRun+380)
07-10 16:31:31.285 716-716/? A/DEBUG:     #07 pc 0000000000034000  /data/app/com.example.huchengzhi.videocompressapp-2/lib/arm64/libjx_ffmpeg_jni.so (Java_com_mabeijianxi_smallvideorecord2_jniinterface_FFmpegBridge_jxCMDRun+188)
07-10 16:31:31.285 716-716/? A/DEBUG:     #08 pc 0000000000830414  /data/app/com.example.huchengzhi.videocompressapp-2/oat/arm64/base.odex (offset 0x4eb000) (int com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.jxCMDRun(java.lang.String[])+152)
07-10 16:31:31.285 716-716/? A/DEBUG:     #09 pc 0000000000830524  /data/app/com.example.huchengzhi.videocompressapp-2/oat/arm64/base.odex (offset 0x4eb000) (int com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.jxFFmpegCMDRun(java.lang.String)+136)
07-10 16:31:31.285 716-716/? A/DEBUG:     #10 pc 000000000081daf8  /data/app/com.example.huchengzhi.videocompressapp-2/oat/arm64/base.odex (offset 0x4eb000) (boolean com.mabeijianxi.smallvideorecord2.FFMpegUtils.captureThumbnails(java.lang.String, java.lang.String, java.lang.String)+140)
07-10 16:31:31.285 716-716/? A/DEBUG:     #11 pc 0000000000ceebb0  /data/app/com.example.huchengzhi.videocompressapp-2/oat/arm64/base.odex (offset 0x4eb000) (void com.example.huchengzhi.videocompressapp.VideoStreamActivity.onCreate(android.os.Bundle)+1892)
07-10 16:31:31.285 716-716/? A/DEBUG:     #12 pc 0000000073d79ba8  /data/dalvik-cache/arm64/system@framework@boot.oat (offset 0x24ce000)
07-10 16:31:31.417 716-716/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_07
07-10 16:31:31.417 716-716/? E/DEBUG: AM write failed: Broken pipe
07-10 16:31:31.439 1399-2301/? E/ActivityManager: Invalid thumbnail dimensions: 0x0

**Comment by mabeijianxi** [comment]
检查你的命令是否符合规范，且打开 Debug 模式，查看生产的日志文件
