### ISSUE TITLE
so文件报错

### ISSUE THREAD

**Issue by dumaokun** [mabeijianxi/small-video-record#177]
错误内容:java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.educ.topuc-2/lib/arm/libutility.so: has text relocations,此错误是在android 6.0以上系统才有的，网上查了一下说让把targetSdkVersion改成低于23，但是我目前的targetVersion就是要写25，请问这个问题您有解决方案吗？手机型号：红米Note 4X。

**Comment by mabeijianxi** [comment]
用 2.x 版本
