### ISSUE TITLE
转码时间好长啊，是不是我设置的参数有问题，求救！！！！！

### ISSUE THREAD

**Issue by MasterXwx** [mabeijianxi/small-video-record#178]

**Comment by MasterXwx** [comment]
MediaRecorderConfig config = new MediaRecorderConfig.Buidler()
                        .fullScreen(true)
                        .smallVideoWidth(480)
                        .smallVideoHeight(480)
                        .recordTimeMax(30 * 1000)
                        .recordTimeMin(5 * 1000)
                        .maxFrameRate(20)
                        .videoBitrate(200)
                        .captureThumbnailsTime(1)
                        .build();

**Comment by mabeijianxi** [comment]
和手机有关，不是64位的手机不建议全屏录制
