### ISSUE TITLE
在eclipse中运行不了

### ISSUE THREAD

**Issue by zjnbjlj** [mabeijianxi/small-video-record#18]
移植到eclipse中运行会报错 请问是为什么
logcat：java.lang.UnsatisfiedLinkError: No implementation found for void com.wzcc.recordvideo.UtilityAdapter.FFmpegInit(java.lang.Object, java.lang.String) (tried Java_com_wzcc_recordvideo_UtilityAdapter_FFmpegInit and Java_com_wzcc_recordvideo_UtilityAdapter_FFmpegInit__Ljava_lang_Object_2Ljava_lang_String_2)

**Comment by zjnbjlj** [comment]
at com.wzcc.recordvideo.UtilityAdapter.FFmpegInit(Native Method)

**Comment by mabeijianxi** [comment]
JNI最基本的常识，用别人的SO库请勿修改相应路径。 com.wzcc.recordvideo.UtilityAdapter肯定是不行的。

**Comment by mabeijianxi** [comment]
JNI最基本的常识，用别人的SO库请勿修改相应全类名。 com.wzcc.recordvideo.UtilityAdapter肯定是不行的
