### ISSUE TITLE
record2 中 录制的视频，播放时间比录制时间短

### ISSUE THREAD

**Issue by yeadong** [mabeijianxi/small-video-record#181]
好像是把录制视频的时间压缩了 播放的时候有快进的效果，比录制时间要短很多。

**Comment by yeadong** [comment]
画面和语音播放的时候都同时快进，不知道这个issue怎么解决啊。在record1中的是没有这个问题的，我猜测可能是底层的ffmpeg造成的。

**Comment by mabeijianxi** [comment]
是扫描下载 APK 试的么？配置参数是什么？机型？

**Comment by mabeijianxi** [comment]
短很多是短多少

**Comment by yeadong** [comment]
不是扫描的，是源代码编译运行的。配置参数都没变，机型：红米 和 三星的都有这个问题。

**Comment by yeadong** [comment]
扫码下载的也是这个问题

**Comment by mabeijianxi** [comment]
我没出现过你说的问题，你快具体快了多少，红米三星也不是机型啊。。。，你打开缓存目录看单独的音频与视频分别的时长是多少，合成后的 MP4视频又是多少，是否一样，又是否和你录制时设置的一样

**Comment by yeadong** [comment]
我用的是红米1 和三星c5测试的 直接扫码下载的app，播放的时候明显感觉快很多，比如录制7秒的视频，视频长度记录的确是是7秒，但播放的时候大概4秒的样子。单独的图像可能不易识别。

**Comment by yeadong** [comment]
单独的音频也是加速播放的

**Comment by mabeijianxi** [comment]
单独的 H264视频用腾讯视频都能播的，可能是采集的问题了，周末我看能不能找到手机试试

**Comment by yeadong** [comment]
嗯 谢谢了

**Comment by Lupwsky** [comment]
魅族U20，录制视频的时候也出现了这种问题，录制30秒的视频，播放到12秒的样子，视频不动了，但播放时间确实有30秒，而且也有声音

**Comment by memoryed** [comment]
三星G7509   录制时间比实际播放时间要长一些

**Comment by yeadong** [comment]
荣耀8也是这个问题，声音相对视频播放要短。

**Comment by mabeijianxi** [comment]
这个问题应该只在小部分手机上出现，我试了很多手机也没法复现，所以暂时不能修复，这个问题先放这里，我尽量找到你们说的这些手机，还有其他机型还出现这问题的也可以在这里添加下

**Comment by yeadong** [comment]
博主 您好，这个问题其实视频部分是没事的，就是音频部分播放很快，您可以念篇文章，播放的速度要比录制的快一倍的。就是图像还没完 声音新停止了

**Comment by mabeijianxi** [comment]
@yeadong 我又试了我的手机还是没出现你的问题，单独播放音频速度正常不？

**Comment by mabeijianxi** [comment]
@yeadong 你把 jx_yuv_encode_h264.cpp 里面的 pCodecCtx->thread_count = 12 改成 1或者2看看效果

**Comment by mabeijianxi** [comment]
@yeadong 不行你再在 jx_pcm_encode_aac.cpp 里把 pCodecCtx->thread_count =1 注释放开试试

**Comment by yeadong** [comment]
嗯 好的 谢谢

**Comment by mabeijianxi** [comment]
@yeadong 试完了告诉我下结果，现在我能想到的就是低端手机核心数太少，视频编码暂用太多线程，导致音频线程切换频繁，被切走的时间里这段音频可能就丢失了

**Comment by yeadong** [comment]
两个都改成了1，还是不行，声音播放仍很快。编码用的时间更长了。

**Comment by yeadong** [comment]
最开始我以为是音频缓冲区覆盖，可您用的是队列，多线程，不应该丢失啊，排除这个原因，会不会是音频时间戳的问题呢？

**Comment by mabeijianxi** [comment]
@yeadong 写不写时间戳都一样的，是根据采样率来算的，采样率用的44100，如果设备实际采样率达不到这个数也肯能加速播放，按理说不应该啊，一般手机都能达到啊，这样你打开 AudioRecorder.java 把 mSampleRate改成16000，然后在 jx_pcm_encode_aac.cpp 里把 pCodecCtx->sample_rate 写死 16000

**Comment by yeadong** [comment]
嗯 这个以前改过 好像是出现哒哒的噪音 我再试试吧

**Comment by yeadong** [comment]
有开机枪类似的噪音，不过语音是放缓了

**Comment by mabeijianxi** [comment]
说明你的采样率确实可能没达到，我用我的手机16000声音也是正常的，你现在用的什么手机试的？你用 demo1试试呢，demo1的也是44100的

**Comment by yeadong** [comment]
改成22050速率就正常了 不过还很大的有噪音

**Comment by yeadong** [comment]
对 demo1是正常的，这个采样频率怎样动态的获得呢？

**Comment by yeadong** [comment]
我现在用的是酷派f2

**Comment by mabeijianxi** [comment]
我暂时不知道动态获取的方法，看来在低端机上音频确实有点点问题，这个得慢慢调，前提我能搞到一个这样的手机...蛋疼

**Comment by yeadong** [comment]
嘿嘿 开来速率是采样频率决定了的 不过为什么在demo1中的也是44100，却播放正常，这个还真搞不明白啊

**Comment by mabeijianxi** [comment]
秒拍不知道多少人写的，又迭代了那么久。。。多半是我底层有些配置不对，得慢慢调...，你那边有手机可以尝试下

**Comment by yeadong** [comment]
嗯 好的 我再尝试尝试其他参数

**Comment by yeadong** [comment]
这个问题暂时解决了，把音频采样调到8000，音频缓冲mMinBufferSize调到2048，就能正常播放了。

**Comment by bingaicao** [comment]
issues:189的，使用record2录制视频，声音和画面不通过，声音过快，帧数20，视频比特率580000。使用小米4C手机。

**Comment by bingaicao** [comment]
应该就是音频采样和mMinBufferSize设置不匹配导致的，record1就没有这个问题，所以请问record1其他平台的so库哪里有呢？

**Comment by mabeijianxi** [comment]
@yeadong 不用调采样率，44100的兼容性最好的。把缓存区改成 2048就可以了，我晚点把其他问题改了发个版本，辛苦你弄了这么久

**Comment by bingaicao** [comment]
缓存区改成2048，我测试一部三星手机，也会出现问题

**Comment by mabeijianxi** [comment]
@bingaicao 不应该了，你上你修改的代码看下

**Comment by bingaicao** [comment]
if (mSampleRate != 8000 && mSampleRate != 16000 && mSampleRate != 22050 && mSampleRate != 44100) {
			mMediaRecorder.onAudioError(MediaRecorderBase.AUDIO_RECORD_ERROR_SAMPLERATE_NOT_SUPPORT, "sampleRate not support.");
			return;
		}

		int mMinBufferSize = AudioRecord.getMinBufferSize(mSampleRate, AudioFormat.CHANNEL_IN_MONO, AudioFormat.ENCODING_PCM_16BIT);

		if (AudioRecord.ERROR_BAD_VALUE == mMinBufferSize) {
			mMediaRecorder.onAudioError(MediaRecorderBase.AUDIO_RECORD_ERROR_GET_MIN_BUFFER_SIZE_NOT_SUPPORT, "parameters are not supported by the hardware.");
			return;
		}
		mMinBufferSize = 2048;
		mAudioRecord = new AudioRecord(android.media.MediaRecorder.AudioSource.MIC, mSampleRate, AudioFormat.CHANNEL_IN_MONO, AudioFormat.ENCODING_PCM_16BIT, mMinBufferSize);
		if (null == mAudioRecord) {
			mMediaRecorder.onAudioError(MediaRecorderBase.AUDIO_RECORD_ERROR_CREATE_FAILED, "new AudioRecord failed.");
			return;
		}
好像可以了，但是声音有点呲呲的背景。

**Comment by mabeijianxi** [comment]
没降噪。先解决了这个同步问题再说 @bingaicao

**Comment by bingaicao** [comment]
第一次可以，后面再次录制，声音语速正确了，但是，声音和画面不同步，声音先播放完了，三星手机SM-G9008v Android6.0

**Comment by bingaicao** [comment]
@mabeijianxi 我是使用使用在腾讯云的活体检测哪里，现在三星手机就是声音先播放完了，但是语速正常了。可以识别通过，很感谢你的代码。这个问题麻烦您有空看看

**Comment by mabeijianxi** [comment]
好的
