### ISSUE TITLE
关于vivo手机录制崩溃的

### ISSUE THREAD

**Issue by liulance** [mabeijianxi/small-video-record#182]
#00 pc 000f039e /data/app/com.instreet.instreet-2/lib/arm/libutility.so (action_incomedata+257) [armeabi-v7a]
--
2 #01 pc 000eb7b5 /data/app/com.instreet.instreet-2/lib/arm/libutility.so (Java_com_yixia_videoeditor_adapter_UtilityAdapter_RenderDataYuv+72) [armeabi-v7a]
3 #02 pc 000dcd19 /system/lib/libart.so (art::JValue art::interpreter::ExecuteSwitchImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+19576) [armeabi-v7a]
4 java:
5 mabeijianxi.camera.MediaRecorderNative.onPreviewFrame(MediaRecorderNative.java:76)
6 android.hardware.Camera$EventHandler.handleMessage(Camera.java:1234)
7 android.os.Handler.dispatchMessage(Handler.java:102)
8 android.os.Looper.loop(Looper.java:148)
9 android.app.ActivityThread.main(ActivityThread.java:5563)
10 java.lang.reflect.Method.invoke(Native Method)
11 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
12 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

在vivo手机上出现崩溃，bug统计上面的错误信息如上，版本是1.2.0，貌似是.so库的问题，请问应该如何解决，谢谢

**Comment by mabeijianxi** [comment]
用 2.x 吧，1.x 的 so 问题修复不了，只能解决 Java 的

**Comment by liulance** [comment]
用你的demo拍摄没问题，是不是.so库复制的不对？

**Comment by mabeijianxi** [comment]
如果你项目里面没有其他架构的so 的话直接 copy 到 armeabi-v7a 下应该是没问题的，前提是你按照集成步骤和使用方法来的

**Comment by liulance** [comment]
我项目里面还有其他的so库，可以直接把demo armeabi-v7a下面的so库拷到项目对应的文件夹里面吗？

**Comment by mabeijianxi** [comment]
就是架构不全的问题，是能解决的，自己查查吧。2.x是全的，就方便些。
