### ISSUE TITLE
record2.0在小米三机型上崩溃

### ISSUE THREAD

**Issue by 815443917** [mabeijianxi/small-video-record#184]
demo在小米三机型上崩溃
![img_0280](https://user-images.githubusercontent.com/21506368/28157679-d68e782e-67e9-11e7-9504-4d8e76bb8630.JPG)
![qq 20170713161952](https://user-images.githubusercontent.com/21506368/28157680-d68ef5ce-67e9-11e7-88a9-ed2be111fb19.png)
![qq 20170713162006](https://user-images.githubusercontent.com/21506368/28157681-d69030e2-67e9-11e7-8820-364ca0129912.png)

**Comment by mabeijianxi** [comment]
你传的参数是什么鬼，到哪奔溃的

**Comment by 815443917** [comment]
传默认的参数  保存视频的时候就崩溃了，个人觉的应该是视频在做压缩处理的时候出现的问题
