### ISSUE TITLE
导入最新2.0源码之后编译不通过的问题

### ISSUE THREAD

**Issue by androidCoderxiao** [mabeijianxi/small-video-record#186]
请问下，编译   SmallVideoLib2\src\main\cpp\jx_jni_handler.cpp 报错 Error:(58, 5) error: cannot use 'try' with exceptions disabled ，使用NDK 版本为R12b,各种方法尝试后未果，麻烦了

**Comment by mabeijianxi** [comment]
使用 R14或者最新版试试

**Comment by gyf19** [comment]
@androidCoderxiao  你解决了吗？  我下载ndk r14b 好像不行呢

**Comment by likebamboo** [comment]
@gyf19  修改 SmallVideoLib2\build.gradle  文件： `cppFlags` 加上 ` -fexceptions` , 如下：
```
externalNativeBuild {
    cmake {
        cppFlags "-std=c++11 -fexceptions"
    }
}
```

**Comment by gyf19** [comment]
OK  谢谢。  我也解决了
