### ISSUE TITLE
怎么取消log

### ISSUE THREAD

**Issue by csr91706** [mabeijianxi/small-video-record#188]
每次提价git，都会出现这些文件，请问怎么可以不生成这些

![8201cb9d-f1ae-8f0f-1651-1fe507e1ef2a](https://user-images.githubusercontent.com/7697993/28204130-3bd09094-68af-11e7-86b9-82542e094c5f.png)

**Comment by mabeijianxi** [comment]
自己加入忽略文件。。。，
