### ISSUE TITLE
视频压缩，声音过快导致不同步问题

### ISSUE THREAD

**Issue by bingaicao** [mabeijianxi/small-video-record#189]

**Comment by mabeijianxi** [comment]
这个问题应该只在小部分手机上出现，我试了很多手机也没法复现，所以暂时不能修复

**Comment by mabeijianxi** [comment]
去另外一个 Issues [ https://github.com/mabeijianxi/small-video-record/issues/181]( https://github.com/mabeijianxi/small-video-record/issues/181) 里把你机型贴下吧，到时候一起解决,这个先关了

**Comment by bingaicao** [comment]
使用第二版压缩的，第一版没有问题，我上班也测试下，是不是码率提高导致。谢谢您的回复，库很棒*^_^*



发自我的小米手机
在 马北剑西 <notifications@github.com>，2017年7月16日 16:14写道：

这个问题应该只在小部分手机上出现，我试了很多手机也没法复现，所以暂时不能修复

**Comment by bingaicao** [comment]
好的



发自我的小米手机
在 马北剑西 <notifications@github.com>，2017年7月16日 16:18写道：

去另外一个 Issues https://github.com/mabeijianxi/small-video-record/issues/181 里把你机型贴下吧，到时候一起解决,这个先关了

**Comment by bingaicao** [comment]
请问record1有其他平台的so库吗？谢谢了



发自我的小米手机
在 马北剑西 <notifications@github.com>，2017年7月16日 下午4:18写道：

去另外一个 Issues https://github.com/mabeijianxi/small-video-record/issues/181 里把你机型贴下吧，到时候一起解决,这个先关了
