### ISSUE TITLE
本地视频压缩没有反应

### ISSUE THREAD

**Issue by wf474606538** [mabeijianxi/small-video-record#190]
作者你好:我在华为mate9上面进行本地视频压缩没有反应；在小米MI2本地视频压缩也没有反应

**Comment by mabeijianxi** [comment]
debug 看走到哪里了，多半又是视频都没选上

**Comment by wf474606538** [comment]
视频路径是有的,走到 OnlyCompressOverBean onlyCompressOverBean = new LocalMediaCompress(config).startCompress();	报了nullpoint.

**Comment by mabeijianxi** [comment]
具体哪里报的啊

**Comment by mabeijianxi** [comment]
你不会没初始化吧。。。

**Comment by wf474606538** [comment]
我只做本地视频存储需要初始化:拍摄视频缓存路径和拍摄

**Comment by wf474606538** [comment]
我只做本地视频存储需要初始化:拍摄视频缓存路径和拍摄吗？

**Comment by mabeijianxi** [comment]
你把 initSmallVideo 里面代码执行下吧，需要初始化的，java 与底层都需要初始化

**Comment by wf474606538** [comment]
好的,谢啦
