### ISSUE TITLE
小米1s初始化就崩溃4.2.2系统

### ISSUE THREAD

**Issue by csr91706** [mabeijianxi/small-video-record#193]
![nvdsf ogsfa i7xczf_ m1](https://user-images.githubusercontent.com/7697993/28257163-28ef5372-6afb-11e7-96de-e36541784411.png)
![qg u b8lxrp375 hmm tuxp](https://user-images.githubusercontent.com/7697993/28257165-3008fdde-6afb-11e7-85e0-0eb27107d81f.png)

**Comment by mabeijianxi** [comment]
先直接扫描下载的apk 试试

**Comment by mabeijianxi** [comment]
扫描下载的没问题就检查下是不是集成出的问题

**Comment by mabeijianxi** [comment]
这个问题可能是老版本手机的一个 bug ，与so 加载的先后顺序有关，你把加载顺序改成这样试试 `System.loadLibrary("avutil");
        System.loadLibrary("fdk-aac");
        System.loadLibrary("avcodec");
        System.loadLibrary("avformat");
        System.loadLibrary("swscale");
        System.loadLibrary("swresample");
        System.loadLibrary("avfilter");
        System.loadLibrary("jx_ffmpeg_jni");`
