### ISSUE TITLE
三星G7509  录制返回崩溃

### ISSUE THREAD

**Issue by memoryed** [mabeijianxi/small-video-record#195]
视频录制几秒，返回，放弃这段视频  直接就停止运行了

**Comment by lixiaohui333** [comment]
对啊  我也遇到这个问题了 魅蓝也会有

**Comment by mabeijianxi** [comment]
直接扫描下载也是么?

**Comment by memoryed** [comment]
是的  直接扫描下载也会出这样的问题，问题可能出在这个位置public static native void nativeRelease();

**Comment by mabeijianxi** [comment]
@memoryed 好的，我等下看看云测上有没有这个机型

**Comment by memoryed** [comment]
在Java_com_mabeijianxi_smallvideorecord2_jniinterface_FFmpegBridge_nativeRelease这个方法中加上了try catch崩溃没有了，看你有更好的方案吗

**Comment by mabeijianxi** [comment]
应该是一个多线程的问题，我改了下，方便留下邮箱不，我给你发下 新的apk试试

**Comment by mabeijianxi** [comment]
我这边没改的时候试了10次基本才出现一次，改了后云测上倒是没出现了，你那边得试一下。
![image](https://user-images.githubusercontent.com/15715756/28300770-4e651d9e-6bb4-11e7-91f2-bb9e42a4923d.png)

**Comment by memoryed** [comment]
ychao0319@foxmail.com 我的邮箱

**Comment by mabeijianxi** [comment]
@memoryed 已发
