### ISSUE TITLE
有什么办法可以不生成这些文件

### ISSUE THREAD

**Issue by csr91706** [mabeijianxi/small-video-record#198]
每次
![0a470fe4-3c60-c65d-6a31-10cc2a552507](https://user-images.githubusercontent.com/7697993/28353644-428e7b7e-6c8f-11e7-8887-edd178aff7ec.png)
编译后都会产生

**Comment by mabeijianxi** [comment]
这是临时文件，肯定得产生啊，不然怎么编译
