### ISSUE TITLE
摄像头设置参数错误

### ISSUE THREAD

**Issue by tczyb** [mabeijianxi/small-video-record#2]
java.lang.RuntimeException: setParameters failed
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.hardware.Camera.native_setParameters(Native Method)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.hardware.Camera.setParameters(Camera.java:2110)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at mabeijianxi.camera.MediaRecorderBase.startPreview(MediaRecorderBase.java:613)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at mabeijianxi.camera.MediaRecorderBase.surfaceCreated(MediaRecorderBase.java:700)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.view.SurfaceView.updateWindow(SurfaceView.java:597)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:179)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2057)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1109)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6046)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:606)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.os.Looper.loop(Looper.java:152)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5497)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
09-10 09:52:35.205 27751-27751/com.mabeijianxi.smallvideo E/Yixia: startPreview fail :setParameters failed

**Comment by mabeijianxi** [comment]
配置builder的时候，视频尺寸的宽度请勿随意传入，需要根据手机摄像头支持的参数传入。里面每一个参数都有详细注释，请细读后传入！
