### ISSUE TITLE
关于2.0最新Demo 在三星NOTE3  盖世4等手机崩溃的问题

### ISSUE THREAD

**Issue by androidCoderxiao** [mabeijianxi/small-video-record#201]
BUG 描述：将录制时间设置为30秒，开始后大概20秒左右就会蹦，几乎是100%概率，麻烦大神看看咋回事
系统： 4.3和4.4
日志如下：
![default](https://user-images.githubusercontent.com/19202943/28396586-0050ffa2-6d2f-11e7-89ed-197185424077.png)
![1](https://user-images.githubusercontent.com/19202943/28396592-0c489bc6-6d2f-11e7-8032-76c1b16f8d95.png)

**Comment by mabeijianxi** [comment]
问题已确认，修改中，晚点提交你再试试

**Comment by androidCoderxiao** [comment]
好的 ，感谢，我一会试试 。

**Comment by mabeijianxi** [comment]
2.0.3已修复请确认

**Comment by androidCoderxiao** [comment]
已确认修复 ，辛苦了 。
