### ISSUE TITLE
record2魅族3上闪退bug

### ISSUE THREAD

**Issue by KarasJoker** [mabeijianxi/small-video-record#203]
献上日志。顺便问一下大神。我自己写了一个相机，在小米5Android7.0不能拍照，就是那个aotofocus的参数success为false。是什么问题。望大神指点

**Comment by KarasJoker** [comment]
![qq 20170721144319](https://user-images.githubusercontent.com/24607442/28452234-3c546e4e-6e24-11e7-8aea-dfa3276cff34.png)

**Comment by mabeijianxi** [comment]
库版本号？这个问题在2.0.3是已经修复了的

**Comment by KarasJoker** [comment]
哦，是么。等我试一下的

**Comment by mabeijianxi** [comment]
三天了也不回个话~~

**Comment by KarasJoker** [comment]
对不起，大神。由于公司有一些其他事情要处理，所以忘了回复您了。不要生气啊，我有罪。还是崩溃。献上log和截图，奇怪的是居然没有报错信息。
![img_0282](https://user-images.githubusercontent.com/24607442/28511194-a7da3de0-707e-11e7-90cf-230f4c82e08a.JPG)
![8ad2bb27-48da-4a7b-a75a-a50a67171d63](https://user-images.githubusercontent.com/24607442/28511208-c2eddf06-707e-11e7-9596-6f8e2483fb65.png)
