### ISSUE TITLE
增加剪切本地视频视频的功能

### ISSUE THREAD

**Issue by gyf19** [mabeijianxi/small-video-record#206]
觉得 FFMpegUtils.java 文件 增加 下面代码， 不知道是否正确？
如果可以的话， pull 一下

/**
 * 视频剪切
 * 
 * @param videoPath 视频路径
 * @param outputPath 截图输出路径
 * @param ss 剪切起始时间，例如00:00:28
 * @param t 剪切结束时间，例如00:00:58
 * @return
 */
public static boolean sectionVideo(String videoPath, String outputPath, String ss, String t) {
	//ffmpeg -ss 00:00:28 -i "int.mp4f" -acodec copy -vcodec copy -t 00:00:58 output.mp4
	FileUtils.deleteFile(outputPath);
	if (ss == null)
		ss = "";
	else
		ss = " -ss " + ss;
	String cmd = String.format("ffmpeg -d stdout -loglevel verbose -i \"%s\" %s -t %s -acodec copy -vcodec copy \"%s\"", videoPath, ss, t, outputPath);
	return   FFmpegBridge.jxFFmpegCMDRun(cmd)==0 ;
}

**Comment by gyf19** [comment]
本地视频太大， 业务需求只是 视频一小部分。

**Comment by mabeijianxi** [comment]
你往 dev 分支上 Pull Request 吧，感谢

**Comment by gyf19** [comment]
@mabeijianxi  已经pull了

**Comment by gyf19** [comment]
@mabeijianxi  我电脑没有NDK ， 所以不能编译测试。   麻烦你测试一下
