### ISSUE TITLE
有的android机不支持

### ISSUE THREAD

**Issue by jacky1234** [mabeijianxi/small-video-record#21]
这个库应该是从 VitamioRecorderLibrary 支持而来，里面的so也是一样大，当时做的时候有个缺陷，有点cpu架构是不支持的，比如：

`private final String[] CPU_UNSUPPORT_ARRAY = new String[]{"arm64-v8a"};`

是不支持的，出现unsatified linked error错误。因为是so包方法找不到，try catch 也是得不到的。所有我加了是否支持本机cpu的判断。  希望可以解决这个问题，让这个库的支持性更广！

**Comment by mabeijianxi** [comment]
这个对x86的是不支持的，arm的应该没问题。重新编译FFmpeg后会解决这些问题，但SO库个数会增多
