### ISSUE TITLE
small-video-record 2.0.3 版本 NoSuchMethodError 错误

### ISSUE THREAD

**Issue by gyf19** [mabeijianxi/small-video-record#221]
录制完成， 程序闪退。 
java.lang.NoSuchMethodError: no static method "Lcom/mabeijianxi/smallvideorecord2/jniinterface/FFmpegBridge;.notifyState(IF)V"

**Comment by gyf19** [comment]
使用 添加依赖 方式安装 的

**Comment by mabeijianxi** [comment]
检查下是否开启了混淆，开了是否有 keep

**Comment by gyf19** [comment]
@mabeijianxi   什么时候发新版本？    可以尽快发一个版本吗？ 谢谢

**Comment by mabeijianxi** [comment]
@gyf19 现在还没改什么东西，暂时也没时间迭代，在忙一些其他事情，所以短时间不会发版本了。

**Comment by gyf19** [comment]
@mabeijianxi  我想用视频剪切功能， 目前不想 源码编译方式  导入 small-video-record 。  所以你麻烦发布一下。

**Comment by mabeijianxi** [comment]
你把你命令直接传入就行了，现有代码也是可以用的

2017-08-01 18:39 GMT+08:00 gyf19 <notifications@github.com>:

**Comment by gyf19** [comment]
ok 明白

**Comment by gyf19** [comment]
![qq 20170802142152](https://user-images.githubusercontent.com/233857/28860183-020e4502-778e-11e7-8c38-933d00ab0b70.png)
@mabeijianxi  是这什么问题？

**Comment by gyf19** [comment]
@mabeijianxi  视频剪切指令不能用！ 急

**Comment by gyf19** [comment]
-21474/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-03 10:04:47.870 21474-21474/? A/DEBUG: Build fingerprint: 'HONOR/BLN-AL10/HWBLN-H:7.0/HONORBLN-AL10/C00B373:user/release-keys'
08-03 10:04:47.870 21474-21474/? A/DEBUG: Revision: '0'
08-03 10:04:47.870 21474-21474/? A/DEBUG: ABI: 'arm'
08-03 10:04:47.870 21474-21474/? A/DEBUG: pid: 19401, tid: 19401, name: com.ymq.min  >>> com.ymq.min <<<
08-03 10:04:47.870 21474-21474/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18
08-03 10:04:47.870 21474-21474/? A/DEBUG:     r0 00000000  r1 00000000  r2 00000000  r3 00000002
08-03 10:04:47.870 21474-21474/? A/DEBUG:     r4 c0262a00  r5 fffffffe  r6 00000000  r7 ffad0a60
08-03 10:04:47.870 21474-21474/? A/DEBUG:     r8 ffad0b38  r9 00000000  sl c04ef000  fp 00000000
08-03 10:04:47.870 21474-21474/? A/DEBUG:     ip dcc08cb4  sp ffad0a50  lr dcbe048d  pc dcbd323c  cpsr 600f0030
08-03 10:04:47.873 21474-21474/? A/DEBUG: backtrace:
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #00 pc 0001423c  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (setup_find_stream_info_opts+11)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #01 pc 00021489  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (open_input_file+1216)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #02 pc 00020e9b  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (open_files+246)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #03 pc 00020c87  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (ffmpeg_parse_options+98)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #04 pc 00014c61  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (jxRun+248)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #05 pc 00027639  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (Java_com_mabeijianxi_smallvideorecord2_jniinterface_FFmpegBridge_jxCMDRun+104)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #06 pc 00fdcc69  /data/app/com.ymq.min-1/oat/arm/base.odex (offset 0xedb000)

**Comment by gyf19** [comment]
`-21474/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-03 10:04:47.870 21474-21474/? A/DEBUG: Build fingerprint: 'HONOR/BLN-AL10/HWBLN-H:7.0/HONORBLN-AL10/C00B373:user/release-keys'
08-03 10:04:47.870 21474-21474/? A/DEBUG: Revision: '0'
08-03 10:04:47.870 21474-21474/? A/DEBUG: ABI: 'arm'
08-03 10:04:47.870 21474-21474/? A/DEBUG: pid: 19401, tid: 19401, name: com.ymq.min  >>> com.ymq.min <<<
08-03 10:04:47.870 21474-21474/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18
08-03 10:04:47.870 21474-21474/? A/DEBUG:     r0 00000000  r1 00000000  r2 00000000  r3 00000002
08-03 10:04:47.870 21474-21474/? A/DEBUG:     r4 c0262a00  r5 fffffffe  r6 00000000  r7 ffad0a60
08-03 10:04:47.870 21474-21474/? A/DEBUG:     r8 ffad0b38  r9 00000000  sl c04ef000  fp 00000000
08-03 10:04:47.870 21474-21474/? A/DEBUG:     ip dcc08cb4  sp ffad0a50  lr dcbe048d  pc dcbd323c  cpsr 600f0030
08-03 10:04:47.873 21474-21474/? A/DEBUG: backtrace:
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #00 pc 0001423c  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (setup_find_stream_info_opts+11)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #01 pc 00021489  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (open_input_file+1216)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #02 pc 00020e9b  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (open_files+246)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #03 pc 00020c87  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (ffmpeg_parse_options+98)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #04 pc 00014c61  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (jxRun+248)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #05 pc 00027639  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (Java_com_mabeijianxi_smallvideorecord2_jniinterface_FFmpegBridge_jxCMDRun+104)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #06 pc 00fdcc69  /data/app/com.ymq.min-1/oat/arm/base.odex (offset 0xedb000)`

**Comment by gyf19** [comment]
-21474/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-03 10:04:47.870 21474-21474/? A/DEBUG: Build fingerprint: 'HONOR/BLN-AL10/HWBLN-H:7.0/HONORBLN-AL10/C00B373:user/release-keys'
08-03 10:04:47.870 21474-21474/? A/DEBUG: Revision: '0'
08-03 10:04:47.870 21474-21474/? A/DEBUG: ABI: 'arm'
08-03 10:04:47.870 21474-21474/? A/DEBUG: pid: 19401, tid: 19401, name: com.ymq.min  >>> com.ymq.min <<<
08-03 10:04:47.870 21474-21474/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18
08-03 10:04:47.870 21474-21474/? A/DEBUG:     r0 00000000  r1 00000000  r2 00000000  r3 00000002
08-03 10:04:47.870 21474-21474/? A/DEBUG:     r4 c0262a00  r5 fffffffe  r6 00000000  r7 ffad0a60
08-03 10:04:47.870 21474-21474/? A/DEBUG:     r8 ffad0b38  r9 00000000  sl c04ef000  fp 00000000
08-03 10:04:47.870 21474-21474/? A/DEBUG:     ip dcc08cb4  sp ffad0a50  lr dcbe048d  pc dcbd323c  cpsr 600f0030
08-03 10:04:47.873 21474-21474/? A/DEBUG: backtrace:
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #00 pc 0001423c  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (setup_find_stream_info_opts+11)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #01 pc 00021489  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (open_input_file+1216)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #02 pc 00020e9b  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (open_files+246)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #03 pc 00020c87  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (ffmpeg_parse_options+98)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #04 pc 00014c61  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (jxRun+248)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #05 pc 00027639  /data/app/com.ymq.min-1/lib/arm/libjx_ffmpeg_jni.so (Java_com_mabeijianxi_smallvideorecord2_jniinterface_FFmpegBridge_jxCMDRun+104)
08-03 10:04:47.873 21474-21474/? A/DEBUG:     #06 pc 00fdcc69  /data/app/com.ymq.min-1/oat/arm/base.odex (offset 0xedb000)

**Comment by lhdboy** [comment]
楼主是如何解决的呢？开了代码混淆就报这个错

**Comment by AsTheWorld** [comment]
-keep class com.mabeijianxi.smallvideorecord2.** {*;}

混淆中加一句这个就解决了
