### ISSUE TITLE
关于版权和 一些小的问题.....

### ISSUE THREAD

**Issue by SmithLiang** [mabeijianxi/small-video-record#23]
如果在商业项目中使用,你说是vitamio家的秒拍SO库,  这会不会涉及到商业版权的问题???
 还有就是 录制完成的时候,你在点击播放的时候,电流声会特别的大,不知道你注意到了没???
 谢谢博主的开源精神,谢谢

**Comment by mabeijianxi** [comment]
具体请看其官网声明
