### ISSUE TITLE
ffmpeg命令行模式，带有""的命令行，会直接崩溃

### ISSUE THREAD

**Issue by fengqingyundan** [mabeijianxi/small-video-record#236]
马老师好，

问一下命令行模式，带有引号的命令行会直接崩溃，这个有什么办法解决吗？

例子如下：
`ffmpeg -i 1.mp4 -i 2.mp4 -filter_complex "[0:v:0] [0:a:0] [1:v:0] [1:a:0] concat=n=2:v=1:a=1 [v] [a]" -map "[v]" -map "[a]" 3-3.mp4`

我发现
FFMpegUtils.captureThumbnails这个的重载方法里面好像也有类似的问题

麻烦有空解答一下，谢谢

**Comment by gzgang** [comment]
去掉 "；并且去掉里面的空格试试

**Comment by fengqingyundan** [comment]
@gzgang 

试过了，不行，仍然感谢

**Comment by fengqingyundan** [comment]
最后证明是ffmpeg编译参数，作者的库没有打开这个过滤器，重新编译就好了，done

**Comment by Zander2014** [comment]
@fengqingyundan 能问一下，是哪个参数吗？
