### ISSUE TITLE
预览画面打不开

### ISSUE THREAD

**Issue by yueshao6800** [mabeijianxi/small-video-record#27]
12-08 15:02:23.540 24724-24724/com.mabeijianxi.smallvideo W/System.err: java.lang.RuntimeException: setParameters failed
12-08 15:02:23.541 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.hardware.Camera.native_setParameters(Native Method)
12-08 15:02:23.541 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.hardware.Camera.setParameters(Camera.java:1695)
12-08 15:02:23.541 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at mabeijianxi.camera.MediaRecorderBase.startPreview(MediaRecorderBase.java:614)
12-08 15:02:23.541 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at mabeijianxi.camera.MediaRecorderBase.surfaceCreated(MediaRecorderBase.java:701)
12-08 15:02:23.541 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.view.SurfaceView.updateWindow(SurfaceView.java:577)
12-08 15:02:23.541 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.view.SurfaceView.access$000(SurfaceView.java:86)
12-08 15:02:23.541 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
12-08 15:02:23.541 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
12-08 15:02:23.542 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2012)
12-08 15:02:23.542 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1125)
12-08 15:02:23.542 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5808)
12-08 15:02:23.542 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:762)
12-08 15:02:23.542 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:575)
12-08 15:02:23.542 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:545)
12-08 15:02:23.542 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:748)
12-08 15:02:23.542 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
12-08 15:02:23.542 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
12-08 15:02:23.542 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.os.Looper.loop(Looper.java:136)
12-08 15:02:23.542 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5028)
12-08 15:02:23.543 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
12-08 15:02:23.543 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
12-08 15:02:23.543 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
12-08 15:02:23.543 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
12-08 15:02:23.543 24724-24724/com.mabeijianxi.smallvideo W/System.err:     at dalvik.system.NativeStart.main(Native Method)
12-08 15:02:23.543 24724-24724/com.mabeijianxi.smallvideo E/Yixia: startPreview fail :setParameters failed

**Comment by mabeijianxi** [comment]
试试新版本1.0.8，应该已经解决你这个问题
