### ISSUE TITLE
在android 6.0上 不能运行

### ISSUE THREAD

**Issue by yingshirun** [mabeijianxi/small-video-record#3]
.so库 会报has text relocations

**Comment by mabeijianxi** [comment]
请在小于等于targetSdkVersion22下开发，不然无法在6.0上运行，原因是FFmpeg里面自己的一个小bug。最新版本的FFmpeg已经解决问题，但是本SO库是在解决前编译的。

**Comment by yingshirun** [comment]
能帮忙编译下支持23的库吗，我们线上版本targetSdkVersion是23， 然后我使用你这个库发现在6.0上不支持23，就把targetSdkVersion改为22了，这样又导致了用户更新失败，6.0的必须要卸载了重新装才可以，，被老板狠批了一顿.....  /(ㄒoㄒ)/~~

**Comment by guobinAndroid** [comment]
我也遇到这个问题，能都支持下23库吗？

**Comment by guobinAndroid** [comment]
我也遇到了同样的问题，能否支持一下23的库啊

**Comment by mabeijianxi** [comment]
亲试，在老版是targetSdkVersion是23，新版targetSdkVersion是22，没有出现更新失败的情况

**Comment by yingshirun** [comment]
是在android 6.0的版本的系统上  先装个 targetSdkVersion23的 在装个 targetSdkVersion22 会更新失败，6.0以下的版本是没问题的
