### ISSUE TITLE
so文件太少了，有的手机根本用不了呀~

### ISSUE THREAD

**Issue by nanchen2251** [mabeijianxi/small-video-record#32]
so文件太少了，有的手机根本用不了呀~

**Comment by mabeijianxi** [comment]
比如说哪些手机？arm系列的都是兼容的

**Comment by nanchen2251** [comment]
主要是体现在一运行到初始化代码就挂掉了。

**Comment by nanchen2251** [comment]
12-15 11:43:54.619 4853-4853/com.maiml.wxrecodervideo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.maiml.wxrecodervideo, PID: 4853
                                                                        java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-support-annotations-25.0.1_90941a77b2b94e164136c426d140cfe0713579d1-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-org.apache.http.legacy_58f2ff08f0f2746636b957e0cdad376f3694e6cb-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-nineoldandroids-2.4.0_7f67ea5b51ab013f3fe120caff2283f598f9b005-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-internal_impl-25.0.1_9098efec2677b06d4c11548ce0afd18cb0f7311f-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-internal_impl-25.0.1_66bdc6fd597173b9eb0e2bc7bd80f064a3fb50b6-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-internal_impl-25.0.1_287994a5282e815beba66f072b0108ea46ce091a-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-internal_impl-25.0.1_21b2d3d7f79d89e6b61beeab417271c9c59f0798-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-internal_impl-25.0.1_212463e6cb7273173f14a9f56c3b96951017fd2c-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-hyphenatechat_3.2.2_123159e4bd6ac7466c1583e194d506743cd1eecd-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-gson-2.2.4_313aff129984a0a45e086871ec03bfcc02e7284e-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-google-play-services_ea0d8b470fdda40aa513a152314319c24f875a59-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-com.android.support-support-vector-drawable-25.0.1_3b38a9a7698def559b702b496b0849f80f7dcfdb-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-com.android.support-support-v4-25.0.1_df2a1f74bfe3e42dced56bd97c4b06b2748bcd31-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-com.android.support-support-media-compat-25.0.1_43df4cd3034933f0a2747550f9d56d490dcb8231-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-com.android.support-support-fragment-25.0.1_53841c8265e72189ca3a822b62f2058e7cc5570f-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-com.android.support-support-core-utils-25.0.1_5acab92fc816d743b734ca54d3d4005b7b9da83a-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-com.android.support-support-core-ui-25.0.1_d2024da0be8aeb7f5f96f4a1d436584f132a2f56-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/instant-run/dex/slice-com.android.support-support-compat-25.0.1_9e684d27ad9e01e82e2ace74d194a9d875a26603-classes.dex", dex file "/data/data/com.maiml.wxrecodervideo/files/

**Comment by nanchen2251** [comment]
不用哪个手机，主要是我们的jniLibs下面分了armv7a v8a x86的
