### ISSUE TITLE
NDK 17.0.4754217 编译失败

### ISSUE THREAD

**Issue by dakun666** [mabeijianxi/small-video-record#343]
SmallVideoLib2 在NDK 17.0.4754217编译失败，报错如下：
![qq20180510-183313](https://user-images.githubusercontent.com/12294061/39865790-9f936ac6-5480-11e8-9224-57bd4675ad16.png)

**Comment by JarvanMo** [comment]
@dakun666 试试这个https://www.jianshu.com/p/70637d7fa5d8

**Comment by Yofun** [comment]
参考：http://blog.51cto.com/4789781/2116935
