### ISSUE TITLE
您好。。能帮我看下这个问题吗。。很急

### ISSUE THREAD

**Issue by dalelufei** [mabeijianxi/small-video-record#38]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ettwit.com.zhangshanggarden-2/base.apk"],nativeLibraryDirectories=[/data/app/ettwit.com.zhangshanggarden-2/lib/arm64, /data/app/ettwit.com.zhangshanggarden-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libutility.so"

**Comment by dalelufei** [comment]
在6.0手机上出现的。我 targetSdkVersion 22

**Comment by heroleon** [comment]
@dalelufei 哥们问一下 你是怎么解决的呢
