### ISSUE TITLE
你好，请问出现这个错误是什么原因 java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader

### ISSUE THREAD

**Issue by zihaozhu1996** [mabeijianxi/small-video-record#40]
我新建一个新的项目按照您的方法行得通，但一整合进自己原来的项目里就报错，在初始化里就错了。

**Comment by heroleon** [comment]
请问这个 问题你解决没有？我也是碰到这个问题了

**Comment by zihaozhu1996** [comment]
你好，我也忘了,你可以试试下面的方法
1. target sdk21以下
2. 将arm...x86...巴拉巴拉里面的so文件弄成一样的，如果没有就从其他的文件夹里复制，或者删掉这个文件夹。总之在这几个文件夹里改吧。


发自网易邮箱大师


在2017年01月10日 15:35 ，leon<mailto:notifications@github.com>写道：


请问这个 问题你解决没有？我也是碰到这个问题了

**Comment by kris-liutao** [comment]
@zihaozhu1996 这个怎么解决的呀  没看懂

**Comment by fems1888** [comment]
一直报这个错java.lang.UnsatisfiedLinkError: No implementation found for int com.yixia.videoeditor.adapter.UtilityAdapter.FilterParserAction(java.lang.String, int) (tried Java_com_yixia_videoeditor_adapter_UtilityAdapter_FilterParserAction and Java_com_yixia_videoeditor_adapter_UtilityAdapter_FilterParserAction__Ljava_lang_String_2I)
                                                                      at com.yixia.videoeditor.adapter.UtilityAdapter.FilterParserAction(Native Method)

**Comment by mabeijianxi** [comment]
2.0.0 正式版刚提交完成，已编译全平台，使用方式也更加解耦，但和以前略有不同，使用前请参看使用文档！
