### ISSUE TITLE
关于录制

### ISSUE THREAD

**Issue by LoginGit** [mabeijianxi/small-video-record#42]
您好，我最近研究录制，想做一个预录制的功能，您的项目很好，但是我想问一下，在我只能给到data音视频数据的情况夏，能否修改供我使用呢，请大神指导一下？

**Comment by mabeijianxi** [comment]
当然可以，但是你采集的音视频你自己得知道它的参数，如分辨率，采样率，帧率等。这样才能初始化底层数据，拿到data你需要对它每一帧进行编码，可以单独用x264，不用庞大的ffmpeg也可以
