### ISSUE TITLE
如何实现全屏了录制调了你的录制比例但是不知道完成后出来的却还是4:3的不全屏的小视频

### ISSUE THREAD

**Issue by pricnehao** [mabeijianxi/small-video-record#50]

**Comment by mabeijianxi** [comment]
全屏录制得修改下ui，不然录制按钮会看不到了，你传入的参数如果不对默认就用4:3

**Comment by mabeijianxi** [comment]
只要你的输入宽度（屏幕短边）没有问题，，常见宽度有480、720、1080等，可通过android API获取摄像头支持的高宽。录制全屏视频你需要做的只是修改录制界面ui即可
