### ISSUE TITLE
请问，如何设置录制视频的方向呢？

### ISSUE THREAD

**Issue by Mask-x** [mabeijianxi/small-video-record#51]
横屏录的视频播放的时候还是按照竖的方向播放的，如何让录制的视频横过来呢？用media recorder录可以设置setOrientationHint，如何让所有机型都强制使用media recorder录制呢？？？

**Comment by mabeijianxi** [comment]
需要设定摄像头参数与传入底层的选择滤镜参数，过段时间我再增加一个配置吧，现在你可以尝试修改源码

**Comment by Mask-x** [comment]
我还发现，录制的视频好像加速了一点点，虽然速度设置的是1f，影音有点不同步

**Comment by Mask-x** [comment]
通过后期ffmpeg旋转视频处理了

**Comment by HolickABC** [comment]
请问怎么用ffmpeg将视频旋转？  看了下博客表示看不太懂。。
