### ISSUE TITLE
多次暂停之后生成的最后的视频会多出几秒来 而且整体看起来有卡顿的感觉

### ISSUE THREAD

**Issue by pricnehao** [mabeijianxi/small-video-record#52]
多次暂停之后生成的最后的视频会多出几秒来 而且整体看起来有卡顿的感觉 我就是改变了宽和高 让他全屏显示了

**Comment by pricnehao** [comment]
设置了 smallVideoWidth(720)，smallVideoHeight(1280)和里面的一个视屏生成的宽高  然后再次多次暂停录制生成的是视频文件就会卡顿了

**Comment by mabeijianxi** [comment]
好的，已经收到反馈，如何核实，尽量下下一版本修复，感谢反馈
