### ISSUE TITLE
你好，我把surfaceview弄成full screen 视频大小设成width1080height1920后，录制过程中出现这个问题

### ISSUE THREAD

**Issue by mccccccmike** [mabeijianxi/small-video-record#54]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/markw/markw:6.0.1/MMB29M/V8.2.1.0.MBECNDL:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 21465, tid: 21465, name: anxi.smallvideo  >>> com.mabeijianxi.smallvideo <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6be9c3be
    r0 00000000  r1 06656700  r2 abe386fc  r3 6be9c3be
    r4 00239880  r5 abfeed48  r6 debcb00c  r7 abfeee20
    r8 00000001  r9 ab845e80  sl ffa089c0  fp ab845e80
    ip 00000000  sp ffa08968  lr e014f37b  pc e014f39e  cpsr 900f0030

backtrace:
    #00 pc 000f039e  /data/app/com.mabeijianxi.smallvideo-2/lib/arm/libutility.so (action_incomedata+257)
    #01 pc 000eb7b5  /data/app/com.mabeijianxi.smallvideo-2/lib/arm/libutility.so (Java_com_yixia_videoeditor_adapter_UtilityAdapter_RenderDataYuv+72)
    #02 pc 000ea919  /system/lib/libart.so (art_quick_generic_jni_trampoline+40)
    #03 pc 000e6221  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
    #04 pc 003eb7ad  /system/lib/libart.so (art_quick_invoke_static_stub+172)
    #05 pc 007fdaec  [stack]

**Comment by mccccccmike** [comment]
你好，视频的高度设置成1920会报错

**Comment by mabeijianxi** [comment]
暂时没有复现
