### ISSUE TITLE
关于录制后视频压缩处理时间过长问题

### ISSUE THREAD

**Issue by FancyOnePoint** [mabeijianxi/small-video-record#58]
视频录制结束后在10s内不管多长压缩处理的时间都有点久,这个能不能把这个时间大幅缩减一下,不然项目用在项目中的用户体验不是很好

**Comment by FancyOnePoint** [comment]
视频转码问题在联发科cpu上应该是没有问题的,但是在高通骁龙手机上录制完视频就直接提示转码失败了

**Comment by mabeijianxi** [comment]
可自由配置，选择高压缩率必然会慢一点，期待H265
