### ISSUE TITLE
这个现在能支持api23吗？或者有什么解决方法吗？

### ISSUE THREAD

**Issue by 920651004** [mabeijianxi/small-video-record#6]
求帮助

**Comment by mabeijianxi** [comment]
一直在迭代，还没时间弄

**Comment by 920651004** [comment]
我解决了那个问题在内层的build.gradle里面添加
ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }
并在gradle.properties中设置android.useDeprecatedNdk=true就可以兼容了
