### ISSUE TITLE
安卓7.0上会弹出一个对话框

### ISSUE THREAD

**Issue by kouhengsheng** [mabeijianxi/small-video-record#66]
我的手机是小米4c，是安卓7.0的版本，运行这个smallVideo后，会弹出一个对话框，里面写着Detected problems with app native libraries(please consult log for detail):libutility.so:text relocations   为什么会弹出这个对话框，这个对话框要怎么去掉。

**Comment by AndroidDevo** [comment]
签名后打包应该就没有了  我的就是这样

**Comment by Hellozhongxin** [comment]
so库只支持23以下

**Comment by java02014** [comment]
@AndroidDevo 你的minSdkVersion ，compileSdkVersion  ，targetSdkVersion ，buildToolsVersion ，supportVersion 是多少？

**Comment by kouhengsheng** [comment]
minSdkVersion 16，compileSdkVersion 22， targetSdkVersion 22， buildToolsVersion "25.0.0"，support:appcompat-v7:22.2.1'

**Comment by mabeijianxi** [comment]
已提交small-video-record2欢迎尝试
