### ISSUE TITLE
视频不能铺满view

### ISSUE THREAD

**Issue by shitou9999** [mabeijianxi/small-video-record#7]
你好，谢谢你的库！我用了这个库android ios 全部是640*480尺寸的视频，为什么android在显示时不能完全的铺满屏幕，左右有黑边，而ios可以正常的显示？原因在那个地方？如果我做视频拉伸处理的话是正常显示的，但是ios说拉伸不好处理，所以再ios机器上不能正常显示。这个问题该怎么处理？多谢

**Comment by shitou9999** [comment]
是不是android录制时候的问题？

**Comment by mabeijianxi** [comment]
你意思是你在录制的时候Builder里面传入的参数是640与480是吗？建议看一下里面的注释，如果宽度是640那么你手机摄像头支持的尺寸里面必须有一个高度为640的尺寸，原因是安卓没处理只支持横屏录制，现在竖屏录制其实是在代码里面旋转过的，所以输入的宽度需要等于一个支持的高度录制出来两边才不会有压缩或者丢失的情况。

**Comment by shitou9999** [comment]
那我前端如果需要显示一个385*380的尺寸，在视频不拉伸，不裁剪的情况下有没有办法办到？谢谢

**Comment by mabeijianxi** [comment]
没法，请使用摄像头所支持的尺寸，以保证不变形,不丢失

**Comment by mabeijianxi** [comment]
但后期会考虑修改剪切规则以适应这种情况。

**Comment by shitou9999** [comment]
恩，多谢！
