### ISSUE TITLE
可以做到保存ts文件但是不打断视频的录制吗？

### ISSUE THREAD

**Issue by qinyang1018** [mabeijianxi/small-video-record#70]

**Comment by mabeijianxi** [comment]
可是你得知道你什么时候需要保存

**Comment by qinyang1018** [comment]
我们的应用有个用户触发的按钮，需求是触发时从当前时间往回截取5s中。而且不能耽误现在的录制。
我目前用打点的方式去解决的  但是这样最后统一处理起来非常耗时。而且中间如果出错了数据就全没了
