### ISSUE TITLE
怎么截取某一个保存的ts文件

### ISSUE THREAD

**Issue by qinyang1018** [mabeijianxi/small-video-record#71]

**Comment by mabeijianxi** [comment]
使用small-video-record1的时候只要你不删除临时文件，那么所有的ts都在的，如果你需要，你需要做的就是去掉我的那段删除代码即可

**Comment by qinyang1018** [comment]
![image](https://user-images.githubusercontent.com/15726024/27001559-7a4cc966-4dff-11e7-8b5c-40f84d731bda.png)
这个文本错了吧  1.2.0beta

我之前一直没有等到回复，就换了其他的方案   我现在研究下你的这个2.0试试看，谢谢你了
