### ISSUE TITLE
建议VCamera so 库替换3.1版本  打包要小很多

### ISSUE THREAD

**Issue by sotoup** [mabeijianxi/small-video-record#74]
官方下载地址
https://www.vitamio.org/download/

UtilityAdapter 也修改加载相应的库

public class UtilityAdapter {
	static {
//		System.loadLibrary("utility");

		System.loadLibrary("ffmpeg");
		System.loadLibrary("openh264");
		System.loadLibrary("vcamera");
	}

...

**Comment by kris-liutao** [comment]
这样会转码失败呢

**Comment by sotoup** [comment]
我试了  没有问题

**Comment by mabeijianxi** [comment]
小与不小在编译FFmpeg的时候都是可以控制的，你开启的功能越多自然越大
