### ISSUE TITLE
请问，录制长视频内存溢出问题

### ISSUE THREAD

**Issue by Mask-x** [mabeijianxi/small-video-record#78]
我录制长视频的时候，最大时长设定5min，在两分钟的时候就内存溢出崩溃了，分辨率960x720，请问如何防止内存溢出呢？？？？

**Comment by Mask-x** [comment]
....改成680x480了。。。能撑到5分钟。。

**Comment by Mask-x** [comment]
= =有什么好方法能录分辨率高点吗。。。。

**Comment by mabeijianxi** [comment]
已提交small-video-record2欢迎尝试
