### ISSUE TITLE
请问如何实现竖屏全屏录制（跟微信朋友圈录制小视频一样）

### ISSUE THREAD

**Issue by abner-wu** [mabeijianxi/small-video-record#85]
现在还实现不了竖屏全部录制，比如我将宽设置成720，高设置成1080，视频转码会失败，如果宽高对调一下，就没有问题，但是不是满屏显示的（用户竖屏录制）。请问怎么才能让其能够正常转码呢？

**Comment by mabeijianxi** [comment]
全屏录制编码速度更更多上了，微信新版的才是全屏的，我怀疑他用了H265或则硬编码，本屌将在第三版本的时候尝试H265与硬编码
