### ISSUE TITLE
本地压缩如何保存

### ISSUE THREAD

**Issue by CJT2325** [mabeijianxi/small-video-record#90]
你好，我想知道使用了本地压缩后，怎么把压缩后的视频保存到本地？

**Comment by mabeijianxi** [comment]
压缩后的视频地址不是已经生成了么，还保存什么，没明白

**Comment by CJT2325** [comment]
嗯，就是我选择本地压缩，选择视频并压缩之后，跳转到一个压缩之后的界面，但是那个视频地址还是我选择压缩的地址，到本地查看这个视频大小还是没有变。因为我也开源了一个模仿微信录视频的组件，想学习一下大哥你这个项目的压缩技术。
