### ISSUE TITLE
录制出来的视频方向不正，请问如何解决好

### ISSUE THREAD

**Issue by ansonlo** [mabeijianxi/small-video-record#91]
录制出来的视频方向不正，在Win PC你用默认播放器就看到是方向错了，请问用哪个API可以解决在生成视频后方向是对的呢？谢谢你回答

**Comment by mabeijianxi** [comment]
这是正常的，因为我们录制的是竖屏视频，底层是旋转过的，你可以试试small-video-record2，底层开源，便于修改
