### ISSUE TITLE
libutility.so has text relocations. This is wasting memory and prevents security hardening. Please fix.

### ISSUE THREAD

**Issue by java02014** [mabeijianxi/small-video-record#94]
在使用您的库时，log总是提示提示，而且还会显示这个提示的dialog（我们的工程的 minSdkVersion = 15，compileSdkVersion = 22， targetSdkVersion = 22， buildToolsVersion = '23.0.3'），这个我该怎么解决呢？

**Comment by mabeijianxi** [comment]
刚刚把所以新版代码整理完成，就这几天发，但是我重写所有c端代码，新版肯定不如老版稳定，但是以后一定会越来越强大

**Comment by MichaelMeng666** [comment]
@mabeijianxi 什么时候更新代码啊，可不可以提前发出来看看，一起改改？

**Comment by java02014** [comment]
@mabeijianxi 是的，到时能把C代码也开放出来，大家可以一起玩耍哈

**Comment by mabeijianxi** [comment]
已提交small-video-record2欢迎尝试
