### ISSUE TITLE
1.2.0无法编译

### ISSUE THREAD

**Issue by qinyang1018** [mabeijianxi/small-video-record#97]
![image](https://user-images.githubusercontent.com/15726024/27001759-ea0e2110-4e03-11e7-8788-eee7ee26bf92.png)
mate8会出现上述错误

**Comment by mabeijianxi** [comment]
你需要有ndk环境，且AS大于2.2，还需要修改cmaklist里面的路径，忘了在做说明，晚上补上

**Comment by mabeijianxi** [comment]
你需要有ndk环境，且AS大于2.2，还需要修改cmakelist.txt里面的路径，忘了在做说明，晚上补上

**Comment by mabeijianxi** [comment]
已经修改脚本，使用最新代码即可
