### ISSUE TITLE
android 7.0 text relocations

### ISSUE THREAD

**Issue by xiadeye** [mabeijianxi/small-video-record#99]
Detected problems with app native libraries 
libutility.so:text relocations
how to fix it?

**Comment by xiadeye** [comment]
06-13 11:59:20.240 10165-10165/com.mabeijianxi.smallvideo W/linker: /data/app/com.mabeijianxi.smallvideo-1/lib/arm/libutility.so has text relocations. This is wasting memory and prevents security hardening. Please fix.

**Comment by mabeijianxi** [comment]
可尝试使用2.0新版
